### ISSUE TITLE
Flake8 Error / Violation Codes

### ISSUE THREAD

**Issue by LucyJimenez** [airspeed-velocity/asv#1008]
Flake8 show some common errors that could be ignored for the repo: 
```
W504,  # W504: Line break occurred after a binary operator
E741  # E741: Do not use variables named 'I', 'O', or 'l
```
TODO [1006](https://github.com/airspeed-velocity/asv/pull/1006)

**Comment by datapythonista** [comment]
It's not clear what's the goal of this issue. Can you update it so it's clear for someone new to the project what they need to do without further context please?

**Comment by datapythonista** [comment]
Closing for now, it's unclear what this is about. Feel free to create a new issue or reopen after adding more information on what this is about.
