### ISSUE TITLE
Changes required to set minimum Python version to 3.7

### ISSUE THREAD

**Issue by datapythonista** [airspeed-velocity/asv#1022]
xref #909

We are removing  support for old versions of Python, and cleaning the code. We'll be moving the CI from Appveyor to GitHub actions (see #985), and running the tests with the minimum and maximum supported Python version. Besides that, we should be updating the required Python version anywhere needed. This includes:
- `setup.py`
- The documentation. If we don't mention the minimum Python version already, we should add it, at least in the installation page.
- Requirements files if a Python version is specified (like `requirements-dev.txt`, `environment.yml`)
- Anywhere else relevant

If there are no objections, the minimum Python version supported by asv will be Python 3.7, the oldest officially supported.

@LucyJimenez do you mind taking care of this please?

**Comment by kanderso-nrel** [comment]
Hello, asv user here!  I'm happy to see the recent maintenance activity for this package and excited about the plans for future development.

> If there are no objections, the minimum Python version supported by asv will be Python 3.8, the oldest officially supported. If that's a problem for anyone, I think 3.8 or 3.7 could also be fine.

Not necessarily a problem, but I'm curious about the motivation to drop support for 3.7, which as I understand still has over a year until EOL: https://devguide.python.org/#status-of-python-branches

**Comment by LucyJimenez** [comment]
Yes, I'm going to start working on this.

**Comment by LucyJimenez** [comment]
@datapythonista  This task was done, was closed with https://github.com/airspeed-velocity/asv/pull/1025
We can close this issue.
