### ISSUE TITLE
[Bug] Use of undefined variable dummy_value

### ISSUE THREAD

**Issue by dorothykiz1** [airspeed-velocity/asv#1023]
The dummy_value variable is being used but not defined and this causes this error **F821 dummy_value not defined**
To solve this it's best to either define /import the dummy_value variable before using it.

To reproduce the bug, run:

-     pip install flake8

-     flake8 --max-line-length=99 test/test_repo_template/asv_test_repo/__init__.py

(this will ignore the max line length according to flake8 from the standard limit of 79 to 99)

**Comment by datapythonista** [comment]
This was fixed
