### ISSUE TITLE
CI on GitHub actions

### ISSUE THREAD

**Issue by LucyJimenez** [airspeed-velocity/asv#1036]
We're currently running the tests in Appveyor for a single version of Python. We want to move the execution of those tests, and we're going to do it in the same way as they're run to start with, and also for Linux only.

There are a few improvements that we can make:

- add better logging to pytest
- run in a matrix of the min and latest python versions
- run in pypy
- add flake8 to the dependencies
- add a job to build the docs

**Comment by LucyJimenez** [comment]
I'm going to close this issue by issues with more specific tasks. See the following issues:
- https://github.com/airspeed-velocity/asv/issues/1022
- https://github.com/airspeed-velocity/asv/issues/1073
- https://github.com/airspeed-velocity/asv/issues/1064

and also this PR:
- https://github.com/airspeed-velocity/asv/pull/1032

**Comment by datapythonista** [comment]
> * add better logging to pytest
> * add flake8 to the dependencies

Are those implemented or with new issues?

**Comment by LucyJimenez** [comment]
> > * add better logging to pytest
> > * add flake8 to the dependencies
> 
> Are those implemented or with new issues?

Done! Those are new issues. I updated the list of issues.
