### ISSUE TITLE
Remove PY2 encoding declaration

### ISSUE THREAD

**Issue by dorothykiz1** [airspeed-velocity/asv#1037]
We are trying to drop any python 2 related syntaxes, comments, or code and replace this with python 3 equivalent code.

Most files in the asv directory have the first-line comment on top of the file `# -*- coding: utf-8 -*-`

The idea is to remove this line from all files as this encoding declaration is related to python 2

**Comment by LucyJimenez** [comment]
As example you can see the PR: https://github.com/airspeed-velocity/asv/pull/1048/files

**Comment by Tushcathy** [comment]
take

**Comment by datapythonista** [comment]
Same here, looks like all them are now gone. Thanks a lot @Tushcathy and @mariamadronah
