### ISSUE TITLE
Remove imports from __future__ module

### ISSUE THREAD

**Issue by dorothykiz1** [airspeed-velocity/asv#1038]
The [__future__](https://docs.python.org/3.5/library/__future__.html) module was introduced in Python 2.1 in order to have access to upcoming features/functions which will lead to incompatibilities with the current implementation and is extended with each version if needed.

Since we are trying to remove python 2 related dependencies. We will remove this particular import from all files for files that have it. 
To be removed: `from __future__ import (absolute_import, division, print_function,
                        unicode_literals)`

**Comment by mariamadronah** [comment]
#taken

**Comment by datapythonista** [comment]
Looks like we've got all them removed now, thanks a lot for taking care @mariamadronah
