### ISSUE TITLE
Marking classes as not benchmarked

### ISSUE THREAD

**Issue by jwodder** [airspeed-velocity/asv#1041]
I'm writing a set of benchmarks that share a lot of common code, and I'd like to use inheritance to put that code in a base class, but I don't want the base class itself to be benchmarked.  Is there a way to do this?  (Note that I can't use parameterization to solve my problem, as some of the variance occurs in the `setup_cache()` method, which isn't parametrized.)

**Comment by jwodder** [comment]
It turns out that making a class abstract prevents it from being benchmarked.  That works for me.

**Comment by trexfeathers** [comment]
That's a newly release feature too - I remember wishing for it two years ago. Thanks ASV team ❤
