### ISSUE TITLE
Fix Flake8 violations for all files in the test/ directory

### ISSUE THREAD

**Issue by dorothykiz1** [airspeed-velocity/asv#1042]
We are trying to clean out all the files to follow Flake8 standards

Use this guide below to install flake8 and how to use it.
[ Flake8 guide](https://siderlabs.com/blog/automatically-review-code-for-python-projects-using-flake8-6fcb056a001a/)

Here are a few steps to follow:
- You will be required to remove the files you would like to work on from the `setup. cfg` file under the `extend` attribute .
- Create a virtual environment `virtualenv venv` venv will be the name for the environment and activate it by running `source venv/bin/activate` these commands are dependent on the operating system. (These are Linux commands, you can find for windows and macOS online)
- Run `pip install flake8` to install flake8
- cd test
- Run `flake8 --exclude="" filename`  for each file in the test directory
- Work on all the highlighted errors

**Comment by datapythonista** [comment]
The `--max-line-length` is not needed, as `flake8` will use the values in `setup.cfg`. And probably easier than removing the excluded files from the config, you can simply pass an empty `--exclude` argument via the command line:

```
$ flake8 --exclude="" test/test_util.py test/test_find.py 
test/test_util.py:7:1: F401 'io' imported but unused
test/test_util.py:8:1: F401 'locale' imported but unused
test/test_util.py:16:1: F401 'time' imported but unused
test/test_util.py:18:1: F401 'six' imported but unused
test/test_util.py:21:1: F401 'asv.console' imported but unused
test/test_util.py:67:5: F841 local variable 'exc' is assigned to but never used
test/test_util.py:82:5: F841 local variable 'exc' is assigned to but never used
test/test_util.py:210:23: E226 missing whitespace around arithmetic operator
test/test_util.py:263:17: E226 missing whitespace around arithmetic operator
test/test_util.py:263:20: E226 missing whitespace around arithmetic operator
test/test_util.py:264:18: E226 missing whitespace around arithmetic operator
test/test_util.py:265:18: E226 missing whitespace around arithmetic operator
test/test_util.py:265:21: E226 missing whitespace around arithmetic operator
test/test_util.py:265:24: E226 missing whitespace around arithmetic operator
test/test_util.py:371:53: E226 missing whitespace around arithmetic operator
test/test_util.py:405:28: E226 missing whitespace around arithmetic operator
test/test_util.py:405:33: E226 missing whitespace around arithmetic operator
test/test_util.py:405:43: E226 missing whitespace around arithmetic operator
test/test_find.py:8:1: F401 'sys' imported but unused
test/test_find.py:35:100: E501 line too long (104 > 99 characters)
test/test_find.py:58:100: E501 line too long (104 > 99 characters)
test/test_find.py:84:5: E303 too many blank lines (2)
test/test_find.py:84:100: E501 line too long (104 > 99 characters)
test/test_find.py:85:43: E231 missing whitespace after ','
test/test_find.py:85:100: E501 line too long (105 > 99 characters)
```

**Comment by dorothykiz1** [comment]
@datapythonista thanks for your comment I will edit the issue to be more clear and that exclude flag is a very good approach.

**Comment by dorothykiz1** [comment]
I will have to split this issue as the files pending are many

**Comment by LucyJimenez** [comment]
@datapythonista @dorothykiz1 I'm going to work on this issue.
