### ISSUE TITLE
Fix Flake8 violations for test/test_web.py and test/test_continuous.py files

### ISSUE THREAD

**Issue by dorothykiz1** [airspeed-velocity/asv#1043]
Flake8, a tool for checking and validating Python syntax. By running flake8 on these files you will be identifying flake8 violations that need to be fixed.

Use this guide below to install flake8 and how to use it.
[ Flake8 guide](https://siderlabs.com/blog/automatically-review-code-for-python-projects-using-flake8-6fcb056a001a/)

Here are a few steps to follow:
- You will be required to remove the files you would like to work on from the `setup. cfg` file under the `extend` attribute.
- Create a virtual environment `virtualenv venv` venv will be the name for the environment and activate it by running `source venv/bin/activate` these commands are dependent on the operating system. (These are Linux commands, you can find for windows and macOS online)
- Run `pip install flake8` to install flake8
- Run `flake8 --exclude="" filename` in this case its `flake8 --exclude="" test/test_web.py` and 
 `flake8 --exclude="" test/test_continuous.py`
- Work on all the highlighted errors

**Comment by datapythonista** [comment]
@dorothykiz1 when you close an issue, can you please add a comment explaining why, and the PR number that closed it, or the issue number that superseded it.. That will help understand what's the status for people following the issue. Thanks!

**Comment by dorothykiz1** [comment]
Thanks @datapythonista  this issue was superseded by [#1042](https://github.com/airspeed-velocity/asv/issues/1042)
