### ISSUE TITLE
Fix out why test failures are detected in Appveyor but not in Github actions

### ISSUE THREAD

**Issue by dorothykiz1** [airspeed-velocity/asv#1060]
Find the commands that have been executed in both Github Actions and Appeveyor. 
Refer to the builds below;

- [Appveyor build](https://paste.ofcode.org/PzrTw83W8pFiPPmTqb4UPg)
- [3.7 build](https://paste.ofcode.org/dD2xe2Ez8nRRnWy6xJjbBV)
- [3.10 build](https://paste.ofcode.org/39aAybDDN8Z9UxsiR6p8Fd5)

Find out the bug causing the test failure in Appveyor and not in Github actions.

**Comment by HaoZeke** [comment]
Closing as the logs have expired :)
