### ISSUE TITLE
Add flake8 to the dependencies

### ISSUE THREAD

**Issue by LucyJimenez** [airspeed-velocity/asv#1074]
This is a minor change to improve the CI file for GitHub actions. 
- Move flake8 dependencies to `requirements-dev.txt`.

**Comment by dorothykiz1** [comment]
#take

**Comment by dorothykiz1** [comment]
> > #take
> 
> This is fine, but just to make sure you're not claiming issues like this for the wrong reason... :)
> 
> In the `pandas` repository, we've got a CI job that monitors comments, and when it finds one with the exact text `take` (no hash at the beginning), it assigns the issue to the commenter. We do this, because unfortunately, GitHub don't let people (except for core devs) to assign issues to themselves. Which is a shame, and there is no reason for it. I've been asking GitHub for this to work, for maybe 4 years now, and not only they didn't implement it, but not a single product manager there know why this limitation exists.
> 
> Having someone assigned to the issue (as opposed to just a comment) is particularly useful because in the list of issues you can filter by the issues that are not assigned to anyone (the ones that nobody is working on). For `asv` this is not that important, but with the volume of pandas would be quite nice to work this way.
> 
> Feel free to use whatever you want to tell the rest of developers of this projects what you're working on. But the `take` in pandas is not implemented here, if that's the reason you use `#take`

> 

we really need this feature, it will help all contributors and also core devs from doing it manually

I will be working on this issue
