### ISSUE TITLE
Remove six as a dependency

### ISSUE THREAD

**Issue by datapythonista** [airspeed-velocity/asv#1076]
xref #909 #1040

Once #1040 is finished, the only main thing missing to completely drop support for python 2 is remove `six` from the list of dependencies. This is in `setup.py`, `requirements-dev.txt`, `environment.yml` (if it exists), the docs and anywhere else. A `grep -R "six" *` should help find any other appareance.

Once this is merged, we should probably close #909 too.

CC: @dorothykiz1

**Comment by dorothykiz1** [comment]
Yes this is noted @datapythonista

**Comment by datapythonista** [comment]
Fixed in #1136
