### ISSUE TITLE
CI problem reported by AppVeyor

### ISSUE THREAD

**Issue by LucyJimenez** [airspeed-velocity/asv#1086]
Sometimes, when we are checking PR related to flake8 issues, the CI from GitHub actions is in green but the CI for AppVeyor reports an error. This CI problem is unrelated to our changes. 

More information on _Originally posted by @datapythonista in https://github.com/airspeed-velocity/asv/issues/1082#issuecomment-1057936154_

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/13194519/156561515-36b81d15-5755-4a63-ae49-53d91c6dd028.png">

**Comment by HaoZeke** [comment]
Closing for now, the issue seems to have resolved itself :)
