### ISSUE TITLE
Call quick_start() function from the tests without having to get input from the user

### ISSUE THREAD

**Issue by dorothykiz1** [airspeed-velocity/asv#1092]
Use of PY3 input() method in asv/commands/quickstart.py file  throws this error;

`FAILED test/test_quickstart.py::test_quickstart - OSError: pytest: reading from stdin while output is captured.`

We need to allow calling this function  from the tests without having to get input from the user, 
and to remove the -s from the pytest calls

Check out this [#1083 ](https://github.com/airspeed-velocity/asv/pull/1083) PR to get more context on this issue

**Comment by datapythonista** [comment]
Thanks @dorothykiz1. A link to the original comment where this was mentioned, so there is more context, would be very helpful here. Anyone checking this issue may benefit from reading the conversation, and understand better where this is coming from.

**Comment by dorothykiz1** [comment]
Let me add this

**Comment by datapythonista** [comment]
Fixed in #1136
