### ISSUE TITLE
Fix flake8 violations for files on asv

### ISSUE THREAD

**Issue by LucyJimenez** [airspeed-velocity/asv#1099]
We are trying to clean out all the files to follow Flake8 standards.
```
- setup.py
- asv/environment.py
- asv/template/benchmarks
- asv/machine.py
- asv/graph.py
- docs/source/conf.py
- asv/results.py
- asv/runner.py
- asv/benchmarks.py
```

Use this guide below to install flake8 and how to use it. Flake8 guide.

Here are a few steps to follow:
- You will be required to remove the files you would like to work on from the `setup. cfg` file under the exclude attribute.
- Create a virtual environment virtualenv venv venv will be the name for the environment and activate it by running source venv/bin/activate these commands are dependent on the operating system. (These are Linux commands, you can find for windows and macOS online).
- Run pip install flake8 to install flake8.
- Run flake8 --exclude="" asv/extern/ .
- Work on all the highlighted errors.

**Comment by datapythonista** [comment]
> - .pytest_cache

This one doesn't make sense. It shouldn't be in the exclude list, there is nothing we want to fix there, it's just a cache.

**Comment by LucyJimenez** [comment]
You are right, I'm going to update the list on the description.

**Comment by datapythonista** [comment]
All those seem fixed now.
