### ISSUE TITLE
Error of exit code of asv on the Pandas CI

### ISSUE THREAD

**Issue by LucyJimenez** [airspeed-velocity/asv#1104]
I opened a [PR](https://github.com/pandas-dev/pandas/pull/46013) in the Pandas repo to remove a hack that shows the asv errors and then change a benchmark to fail. The result was that Panda's CI gets green even when benchmarks fail.

Here is the hack for asv:
<img width="892" alt="image" src="https://user-images.githubusercontent.com/13194519/157052778-840d5148-d8e4-4232-b9a6-75fa9ec6e2dd.png">

Here the change on the benchmark:
<img width="880" alt="image" src="https://user-images.githubusercontent.com/13194519/157033808-2db53d79-975d-46f3-bacd-3b8350103426.png">

Here is the output of the CI:
<img width="880" alt="image" src="https://user-images.githubusercontent.com/13194519/154178996-16e8267b-6c74-4030-a05c-d696ee82ee84.png">

**Comment by fangchenli** [comment]
asv master currently doesn't work for pandas

```bash
(pandas-dev) fangchenli@Fangchens-MacBook-Pro-2 asv_bench % asv continuous -f 1.1 upstream/main HEAD
· Creating environments
· Discovering benchmarks
·· Error running /Users/fangchenli/Workspace/pandas-fangchenli/asv_bench/env/45e7123d25d88e958f183355b52ee854/bin/python /opt/homebrew/Caskroom/miniforge/base/envs/pandas-dev/lib/python3.8/site-packages/asv/benchmark.py discover /Users/fangchenli/Workspace/pandas-fangchenli/asv_bench/benchmarks /var/folders/jb/7cnwq8jd06dgkhltmyf8yk200000gn/T/tmptyk9yh1n/result.json (exit status -11)
   STDOUT -------->
   
   STDERR -------->
   

·· Failed to build the project and import the benchmark suite.
```

@datapythonista

**Comment by fangchenli** [comment]
I got the same error on 0.4.2... Not sure why

**Comment by datapythonista** [comment]
This can be implemented with `--strict`, and will be default in #1204
