### ISSUE TITLE
Error when the `locale` import is removed from `test/test_util.py`

### ISSUE THREAD

**Issue by LucyJimenez** [airspeed-velocity/asv#1106]
Flake8 shows that the `locale` library is not used in the file `test/test_util.py`, but when I removed the `import locale` I get an [error in AppVeyor](https://ci.appveyor.com/project/airspeed-velocity/asv/builds/42784236).

<img width="508" alt="image" src="https://user-images.githubusercontent.com/13194519/157090042-40db7689-128c-4fa6-bcf5-84ab0e5c34f0.png">

**Comment by datapythonista** [comment]
This wasn't true, closing
