### ISSUE TITLE
CLN: Remove vendored json minifier

### ISSUE THREAD

**Issue by datapythonista** [airspeed-velocity/asv#1140]
xref #1139 

I didn't check in detail, but I guess the vendored json minifier in `asv/extern/minify_json.py` can be replaced with the next approach using simply the `json` standard library module: https://stackoverflow.com/a/33233406/711705

**Comment by fangchenli** [comment]
We also need to be able to read json file with comments, so still need the minify_json. We could add support for writing config in `pyproject.toml` and deprecated the existing json config file.

**Comment by HaoZeke** [comment]
This is completed in https://github.com/airspeed-velocity/asv/pull/1234
