### ISSUE TITLE
[Sprint] Fix flake8 violations for files on test/__init__.py

### ISSUE THREAD

**Issue by LucyJimenez** [airspeed-velocity/asv#1164]
We are trying to clean out all the files to follow Flake8 standards.
Here are a few steps to follow:
- Create a virtual environment virtualenv venv venv will be the name for the environment and activate it by running source venv/bin/activate these commands are dependent on the operating system. (These are Linux commands, you can find for windows and macOS online).
- Run `pip install flake8` to install flake8.
- Run `flake8 --exclude="" test/__init__.py` .
- Work on all the highlighted errors.
- At the end, you will be required to remove the files you would like to work on from the `setup. cfg` file under the exclude attribute.

For this file, you will find just an issue to solve:
`test/__init__.py:9:1: E402 module level import not at top of file`

**Comment by dorothykiz1** [comment]
closed in #1190
