### ISSUE TITLE
[Sprint] Fix flake8 violations for files on test/test_compare.py

### ISSUE THREAD

**Issue by LucyJimenez** [airspeed-velocity/asv#1165]
We are trying to clean out all the files to follow Flake8 standards.

Here are a few steps to follow:
- Create a virtual environment virtualenv venv venv will be the name for the environment and activate it by running source venv/bin/activate these commands are dependent on the operating system. (These are Linux commands, you can find for windows and macOS online).
- Run `pip install flake8` to install flake8.
- Run `flake8 --exclude="" test/test_compare.py` .
- Work on all the highlighted errors.
- At the end, you will be required to remove the files you would like to work on from the setup. cfg file under the exclude attribute.

For this file you will find the following issues to solve
```
test/test_compare.py:101:30: W291 trailing whitespace
test/test_compare.py:119:100: E501 line too long (108 > 99 characters)
test/test_compare.py:120:100: E501 line too long (100 > 99 characters)
test/test_compare.py:121:100: E501 line too long (102 > 99 characters)
test/test_compare.py:122:100: E501 line too long (108 > 99 characters)
test/test_compare.py:123:100: E501 line too long (114 > 99 characters)
test/test_compare.py:125:100: E501 line too long (103 > 99 characters)
test/test_compare.py:126:100: E501 line too long (107 > 99 characters)
test/test_compare.py:129:100: E501 line too long (102 > 99 characters)
```

**Comment by nicolefrale** [comment]
@LucyJimenez I'm going to work in this one
