### ISSUE TITLE
[Sprint] Use f-strings instead .format() function on asv/plugins/mercurial.py

### ISSUE THREAD

**Issue by LucyJimenez** [airspeed-velocity/asv#1173]
xref [#909](https://github.com/airspeed-velocity/asv/issues/909)

Since we support Python > 3.7 now, we can make use of f-strings, to make code more readable.

As an example, the next asv code:
`machine_env_name = "{}/{}".format(machine, env_name)`
or the next, which is equivalent:
`machine_env_name = "{0}/{1}".format(machine, env_name)`
Could be written as:
`machine_env_name = f"{machine}/{env_name}"`

(note the `f` before the string quotes)

---

The next command returns the list of strings to replace: 

 `grep -R --exclude-dir="build" --exclude="*.css" ".format(" asv/plugins/mercurial.py`

For this file, you will find the following issues to solve:
```
asv/plugins/mercurial.py:        return '{0}::{1} and not {0}'.format(commit_a, commit_b)
asv/plugins/mercurial.py:        return '{0}::{1}'.format(latest_result, self.get_branch_name(branch))
asv/plugins/mercurial.py:        range_spec = self._encode("sort({0}, -rev)".format(range_spec))
asv/plugins/mercurial.py:        return self.get_hash_from_name('p1({0})'.format(name))
asv/plugins/mercurial.py:        return self.get_hashes_from_range(query.format(self.get_branch_name(branch)),
```

**Comment by LucyJimenez** [comment]
I'm going to work on thin one.

**Comment by datapythonista** [comment]
Not useful anymore, and add noise to the issues list.
