### ISSUE TITLE
[Sprint] Use f-strings instead .format() function on asv/environment.py

### ISSUE THREAD

**Issue by LucyJimenez** [airspeed-velocity/asv#1178]
xref [#909](https://github.com/airspeed-velocity/asv/issues/909)

Since we support Python > 3.7 now, we can make use of f-strings, to make code more readable.

As an example, the next asv code:
`machine_env_name = "{}/{}".format(machine, env_name)`
or the next, which is equivalent:
`machine_env_name = "{0}/{1}".format(machine, env_name)`
Could be written as:
`machine_env_name = f"{machine}/{env_name}"`

(note the `f` before the string quotes)

---

The next command returns the list of strings to replace: 

 `grep -R --exclude-dir="build" --exclude="*.css" ".format(" asv/environment.py`

For this file, you will find the following issues to solve:
```
asv/environment.py:            raise util.UserError('Unknown keys in "matrix" configuration: {}, expected: {}'.format(
asv/environment.py:        raise util.UserError("include rule '{0}' does not specify Python version".format(rule))
asv/environment.py:    name.append("py{0}".format(python))
asv/environment.py:            raise ValueError("Invalid matrix key type {0}".format(key))
asv/environment.py:        "No way to create environment for python='{0}'".format(python))
asv/environment.py:        "Unknown environment type '{0}'".format(environment_type))
asv/environment.py:                log.error("Failure creating environment for {0}".format(self.name))
asv/environment.py:            log.info("Installing {0} into {1}".format(commit_name, self.name))
asv/environment.py:            log.info("Uninstalling from {0}".format(self.name))
asv/environment.py:            log.info("Building {0} for {1}".format(commit_name, self.name))
asv/environment.py:        log.debug("Running '{0}' in {1}".format(' '.join(args), self.name))
```

**Comment by LucyJimenez** [comment]
@dorothykiz1 and @datapythonista I'm going to work on this one.

**Comment by datapythonista** [comment]
Not useful anymore, and add noise to the issues list.
