### ISSUE TITLE
[Sprint] Use f-strings instead .format() function on asv/commands/update.py

### ISSUE THREAD

**Issue by LucyJimenez** [airspeed-velocity/asv#1179]
xref [#909](https://github.com/airspeed-velocity/asv/issues/909)

Since we support Python > 3.7 now, we can make use of f-strings, to make code more readable.

As an example, the next asv code:
`machine_env_name = "{}/{}".format(machine, env_name)`
or the next, which is equivalent:
`machine_env_name = "{0}/{1}".format(machine, env_name)`
Could be written as:
`machine_env_name = f"{machine}/{env_name}"`

(note the `f` before the string quotes)

---

The next command returns the list of strings to replace: 

 `grep -R --exclude-dir="build" --exclude="*.css" ".format(" asv/commands/update.py`

For this file, you will find the following issues to solve:
```
asv/commands/update.py:                        log.warning("{}: {}".format(path, err))
asv/commands/update.py:                                log.warning("{}: should be renamed to {}".format(path, new_path))
asv/commands/update.py:                        log.warning("{}: unrecognized file name".format(path))
```

**Comment by asnramos** [comment]
xref #1079

**Comment by datapythonista** [comment]
Not useful anymore, and add noise to the issues list.
