### ISSUE TITLE
[Sprint] Use f-strings instead .format() function on asv/commands/run.py

### ISSUE THREAD

**Issue by LucyJimenez** [airspeed-velocity/asv#1180]
xref [#909](https://github.com/airspeed-velocity/asv/issues/909)

Since we support Python > 3.7 now, we can make use of f-strings, to make code more readable.

As an example, the next asv code:
`machine_env_name = "{}/{}".format(machine, env_name)`
or the next, which is equivalent:
`machine_env_name = "{0}/{1}".format(machine, env_name)`
Could be written as:
`machine_env_name = f"{machine}/{env_name}"`

(note the `f` before the string quotes)

---

The next command returns the list of strings to replace: 

 `grep -R --exclude-dir="build" --exclude="*.css" ".format(" asv/commands/run.py`

For this file, you will find the following issues to solve:
```
asv/commands/run.py:                raise util.UserError('Unknown branch {0} in configuration'.format(exc))
asv/commands/run.py:                log.error('Requested commit hash file "{}" is not a file'.format(hashfn))
asv/commands/run.py:                        log.warning("Unknown commit hash {0} in input file".format(h))
asv/commands/run.py:            "({1} commits * {2} environments * {3} benchmarks)".format(
asv/commands/run.py:                    round_info = " (round {}/{})".format(
asv/commands/run.py:                    "For {0} commit {1}{2}:".format(
asv/commands/run.py:                        log.info("Building for {0}".format(subenv_name))
```

**Comment by Daniet** [comment]
@LucyJimenez 
i will work on this

**Comment by LucyJimenez** [comment]
@datapythonista, this issue has already been resolved.
