### ISSUE TITLE
Make --strict default and remove parameter

### ISSUE THREAD

**Issue by datapythonista** [airspeed-velocity/asv#1199]
I think asv interface can be improved by making `--strict` parameter of the run command to be the default. It makes the command return an exit code != 0 if things break, which I think it's the behavior that user would expect.

I'll also remove the parameter, since ignoring errors can be simply done as `asv | true`.

**Comment by trexfeathers** [comment]
Error 'catching' at the benchmark level - rather than the command line level - is useful for distinguishing between problems in:

* Run execution (environment building, benchmark discovery etc.)
* Benchmark execution

Can you suggest any alternative ways of making this distinction that don't involve just grepping for certain text (an anti-pattern in my book)?

**Comment by trexfeathers** [comment]
That would work great, thanks.

This is useful in our case for speeding up debugging. Many of our benchmarks need to be given access to various paths via env vars. If I just want to confirm run behaviour (env setup, repeat number, interleaving etc.) then it takes literally half as long if I don't need to make sure the benchmarks themselves will run perfectly. Hope that's helpful detail.

**Comment by trexfeathers** [comment]
>I think `asv run` having broken benchmarks and causing a green CI is misleading, and can cause errors fail silently, which is not great.

Agreed

>Asv commands have a huge number of parameters, and anything that can be simplified in the code would also be great.

Agreed

>The run will take the same and will keep going, regardless of the exit code.

Thanks, I had been assuming that `--strict` would cause an _immediate_ exit as soon as there was a benchmark failure. Sorry for the misunderstanding - I've only worked with `--strict` a few times so far.

If `--strict` (or a future default behaviour) just causes a failure exit code at the _end_ of the run then it would indeed be easy enough to do a test run, or to embed in a larger script that publishes whatever results worked, even if some benchmarks failed.

**Comment by datapythonista** [comment]
Ah, cool. That's why I wasn't understanding you. Afaik there is nothing to cancel the build early.

`--strict` is just to return `2` instead of `0` if there are failures: https://github.com/airspeed-velocity/asv/blob/master/asv/commands/run.py#L518
