### ISSUE TITLE
Release 0.6.0

### ISSUE THREAD

**Issue by datapythonista** [airspeed-velocity/asv#1205]
Planning a new release soon. Besides what's already in master (mostly clean up, and dropping py2), I'm planning to have the next issues. Please comment with any other that it's worth waiting a release for:

- #1199
- #1200
- #1201
- #1203
- #1140
- #1028
- Change defaults of environments, and add deprecation warnings, in preparation to remove environment support? see #1031
- Remove vendored code, and add appropriate dependencies instead?
- Add deprecation warnings to UI commands?, which will probably be moved to a separate package (issue for discussion pending)
- Allow to run without a machine file? At least with `--dry-run` that would make sense

CC: @fangchenli @mroeschke @jbrockmendel

**Comment by h-vetinari** [comment]
Any updates on a new release? It seems scipy will [need](https://github.com/scipy/scipy/pull/18857) unreleased asv features, and it would of course be nicer to have a release for those. :)

CC @haozeke

**Comment by HaoZeke** [comment]
> Any updates on a new release? It seems scipy will [need](https://github.com/scipy/scipy/pull/18857) unreleased asv features, and it would of course be nicer to have a release for those. :)
> 
> CC @HaoZeke

Wrapping up the final tasks, should be out this week :)

**Comment by HaoZeke** [comment]
Closed by https://github.com/airspeed-velocity/asv/pull/1321.
