### ISSUE TITLE
How do I run setup_cache with parameters

### ISSUE THREAD

**Issue by arunjose696** [airspeed-velocity/asv#1224]
In ASV setup method it is possible to set parameters as class variables. But this does not seem to work with setup_cache function. How to do something like below?

```python

class xyz:
    params = [1,2]
    param_names = ["param1"]

    def setup_cache(self,param1):
        ....

    def time_dt_accessor(self, series):
        ....
```

**Comment by trexfeathers** [comment]
From [the documentation](https://asv.readthedocs.io/en/stable/writing_benchmarks.html#parameterized-benchmarks):

>Note that `setup_cache` is not parameterized.

You instead need to handle `xyz`'s parameters within `setup_cache()`, for example:

```python
for param in xyz.params:
    do_something(param)
```

[Another example in SciTools/iris](https://github.com/SciTools/iris/blob/dfbc5c2aef0c64918061a4e312f66d94b0beb525/benchmarks/benchmarks/load/__init__.py#L71-L92) .

**Comment by arunjose696** [comment]
that helps
