### ISSUE TITLE
BLD: Distribute wheels

### ISSUE THREAD

**Issue by HaoZeke** [airspeed-velocity/asv#1277]
Currently, only source distributions are on `pypi`. The `setup.py` has logic to continue building where compilers are not present, but an alternative would be to add `cibuildwheel` and also distribute wheels.

**Comment by mattip** [comment]
It might be nice to get some of the improvements over the last few months into a new release too.

**Comment by HaoZeke** [comment]
Related to #1337. Closed by #1341.
