### ISSUE TITLE
RFC: Refactoring out `asv` plugins

### ISSUE THREAD

**Issue by HaoZeke** [airspeed-velocity/asv#1283]
`asv` actually has a very robust plugin ecosystem, which is criminally under-documented. This should be fixed, but also it would be a good idea to spin out parts of the codebase into separate repos. In particular, some features which have been discussed for deprecation could easily be spun out, like the [mercurial plugin](https://github.com/airspeed-velocity/asv/issues/1203).

Additionally, similar to `pytest`, then, additional features would come in at the plugin level, possibly modifying the requirements as needed (e.g. adding `memray`) and would be in repositories like `asv-memray`.

Currently there is also no separation between `plugins` and `environment` managers which seems a bit disingenuous as well.

Does this seem like a good design? If so, the next steps are:
- [ ] Document the `plugin` ecosystem
- [ ] Determine what remains in "core" `asv` and what gets spun out
  - [ ] Move most(?) of the files under `plugins` to their own repo

There might be some extensions to the `plugin` ecosystem required as well, in order to handle plugins in external repos / other locations.

**Comment by HaoZeke** [comment]
@mattip what do you think?

**Comment by mattip** [comment]
Makes sense.

**Comment by mattip** [comment]
Closing, now that the plugin system works.
