### ISSUE TITLE
Soft deprecation of `mem` and `peakmem`

### ISSUE THREAD

**Issue by HaoZeke** [airspeed-velocity/asv#1292]
@mattip and I noticed that no project (on Github) seems to actually use the `pympler` based `mem` and `ctypes` focused `peakmem` benchmarks. These are not as flexible as the standard `time` benchmarks, and might be best spun out into `asv_peakmem` and `asv_asizeof` or something. Using the machinery introduced by #1287

**Comment by dcherian** [comment]
Xarray does use these : https://github.com/pydata/xarray/blob/17c9e8fa50da610990c42f0a49d63754a9a7db0e/asv_bench/benchmarks/rolling.py#L105

but we are happy to migrate to whatever new way there is to track memory.

Thanks for your work here! It was sorely needed

**Comment by HaoZeke** [comment]
> Xarray does use these : https://github.com/pydata/xarray/blob/17c9e8fa50da610990c42f0a49d63754a9a7db0e/asv_bench/benchmarks/rolling.py#L105
> but we are happy to migrate to whatever new way there is to track memory.


Excellent, I'll make sure to run the testsuite against `xarray` and open a PR / Issue for migration.

> Thanks for your work here! It was sorely needed

^_^ You're welcome, and glad to hear it.

**Comment by braingram** [comment]
asdf also uses `peakmem` benchmarks and is also happy to migrate:

https://github.com/asdf-format/asdf/blob/1e9a0497f80fa1a13c496a1727049af5a5ebae5d/benchmarks/asdf.py#L88

The prospect of using memray in the benchmarks is exciting!

Thanks :)

**Comment by Xemorr** [comment]
What is the alternative to mem and peakmem?

**Comment by mattip** [comment]
Closing, this is now delegated to the plugins. Please reopen or open a new issue if there is more to be done.
