### ISSUE TITLE
BUG: Package requires a different Python

### ISSUE THREAD

**Issue by jmccreight** [airspeed-velocity/asv#1294]
Hi. Thanks for ASV. I'm really enjoying it. I have my conf and my suite of benchmarks mostly ready to go, but I have one issue

```
ERROR: Package 'mypackage' requires a different Python: 3.11.3 not in '<3.11,>=3.9'
```
In my conf, i have
```
    "environment_type": "conda",
    "pythons": ["3.9", "3.10"],
```
(among others) so this is surprising.

Indeed, mypackage is not supported for 3.11 and that information is in the pyproject.toml (which is what is apparently triggering the error on package install). I have older commits where this requires-python constraint was not present. In those cases asv runs the benchmarks, supposedly for python 3.10 (say) but if I insert `print(sys.version)` into a benchmark, i get back 3.11.3 in stdout. 

I thought maybe I'd installed asv improperly. So I went back to a fresh conda env and `pip install asv`. This step installed python 3.11 again and I have the same issues.  

Thanks in advance for clues on how I can resolve this.

**Comment by jmccreight** [comment]
I'll be more specific:
```
(asv) ~/fakepath/pywatershed/asv_benchmarks (feat_asv_pws ✘)✭ ᐅ which python3.9                                                                                    17:16:10
/Users/fakeuser/anaconda3/envs/python3.9/bin/python3.9
(asv) ~/fakepath/pywatershed/asv_benchmarks (feat_asv_pws ✘)✭ ᐅ python3.9 --version                                                                                17:16:17
Python 3.9.16
(asv) ~/fakepath/pywatershed/asv_benchmarks (feat_asv_pws ✘)✭ ᐅ asv continuous --verbose --show-stderr --factor 1.5 53a2e51929  6a38b1e507                         17:16:24
Couldn't load asv.plugins.mamba because
No module named 'mamba'
Couldn't load asv.plugins.virtualenv because
No module named 'packaging'
· Running '/opt/local/bin/git config init.defaultBranch'
  OUTPUT -------->
  main
· Running '/opt/local/bin/git rev-parse 6a38b1e507^{commit}'
  OUTPUT -------->
  6a38b1e507b11c481a58c8f2defe6aa4090a876d
· Running '/opt/local/bin/git rev-parse 53a2e51929^{commit}'
  OUTPUT -------->
  53a2e51929eb031fcf6f2f3aafefeee3c03c6bc2
· Running '/opt/local/bin/git config init.defaultBranch'
  OUTPUT -------->
  main
· Creating environments
·· Running '/Users/fakeuser/fakepath/pywatershed/asv_benchmarks/.asv/env/ed39ea94013ef951c2f87729f21b313e/bin/python -c pass'
·· Running '/Users/fakeuser/fakepath/pywatershed/asv_benchmarks/.asv/env/8f19820bd9c341d5d9d38fcd3adea923/bin/python -c pass'
· Discovering benchmarks
·· Running '/opt/local/bin/git rev-parse develop^{commit}'
   OUTPUT -------->
   2b4481149fd1a1cdb32f2b3c8aa23101ec32fce9
·· Running '/opt/local/bin/git -c protocol.file.allow=always submodule deinit -f .'
·· Running '/opt/local/bin/git checkout -f 6a38b1e507b11c481a58c8f2defe6aa4090a876d'
   OUTPUT -------->
   Previous HEAD position was 53a2e51 Merge pull request #148 from EC-USGS/jdhughes-usgs-patch-1
   HEAD is now at 6a38b1e asv prms tests parameterized
·· Running '/opt/local/bin/git clean -fdx'
·· Running '/opt/local/bin/git -c protocol.file.allow=always submodule update --init --recursive'
·· Uninstalling from conda-py3.9-netcdf4-numpy-xarray
·· Running '/Users/fakeuser/fakepath/pywatershed/asv_benchmarks/.asv/env/ed39ea94013ef951c2f87729f21b313e/bin/python -mpip uninstall -y pywatershed'
   OUTPUT -------->
   WARNING: Skipping pywatershed as it is not installed.
·· Running '/opt/local/bin/git name-rev --name-only --exclude=remotes/* --no-undefined 6a38b1e507b11c481a58c8f2defe6aa4090a876d'
   OUTPUT -------->
   feat_asv_pws~1
·· Building 6a38b1e5 <feat_asv_pws~1> for conda-py3.9-netcdf4-numpy-xarray
·· Running '/Users/fakeuser/fakepath/pywatershed/asv_benchmarks/.asv/env/ed39ea94013ef951c2f87729f21b313e/bin/python -mpip wheel --no-deps --no-index -w /Users/fakeuser/fakepath/pywatershed/asv_benchmarks/.asv/env/ed39ea94013ef951c2f87729f21b313e/asv-build-cache/6a38b1e507b11c481a58c8f2defe6aa4090a876d /Users/fakeuser/fakepath/pywatershed/asv_benchmarks/.asv/env/ed39ea94013ef951c2f87729f21b313e/project'
   OUTPUT -------->
   Processing /Users/fakeuser/fakepath/pywatershed/asv_benchmarks/.asv/env/ed39ea94013ef951c2f87729f21b313e/project
     Preparing metadata (pyproject.toml): started
     Preparing metadata (pyproject.toml): finished with status 'done'
   INFO: pip is looking at multiple versions of pywatershed to determine which version is compatible with other requirements. This could take a while.
   ERROR: Package 'pywatershed' requires a different Python: 3.11.3 not in '<3.11,>=3.9'
·· Error running /Users/fakeuser/fakepath/pywatershed/asv_benchmarks/.asv/env/ed39ea94013ef951c2f87729f21b313e/bin/python -mpip wheel --no-deps --no-index -w /Users/fakeuser/fakepath/pywatershed/asv_benchmarks/.asv/env/ed39ea94013ef951c2f87729f21b313e/asv-build-cache/6a38b1e507b11c481a58c8f2defe6aa4090a876d /Users/fakeuser/fakepath/pywatershed/asv_benchmarks/.asv/env/ed39ea94013ef951c2f87729f21b313e/project (exit status 1)
·· Failed: trying different commit/environment
```

**Comment by HaoZeke** [comment]
Thanks for the detailed report! Is the package open-sourced? To test this a bit more?

**Comment by jmccreight** [comment]
Hi @HaoZeke, 

Yes, it is open source
https://github.com/EC-USGS/pywatershed/tree/develop/asv_benchmarks

that's the path to where I keep the asv conf and benchmars directory. You'll see the readme.md in there comments on how the python version installed by conda appears to depend on the environment I specify (without pinning python). To recap this: When I use the full environment.yml (in the root of my repo) that satisfies my maximal pip install, conda uses python3.10. So I have limited my pythons in asv config to 3.10 and I'm using this for now  (though I'd like to use 3.9 as well). The odd thing is that if I reduce my environment more towards the bare essentials, conda installs python 3.11 and I'm back in the position I initially reported. 

It seems like the onus of getting the right python version from conda is on the user. Is that the intent? I saw that if I'm using venv, I have to have the python binaries on the PATH, but my reading of that was that it did not apply to using conda. Of course, I could pin the python version in an env.yaml for asv, but how would that interact with pythons specified in conf? My apologies, I have not had time to look into the asv code for any answers to this. Perhaps this is just a detail for documentation that I'm getting tripped up on.

In any case, it seems like it might be good to check that the expected version of python is being used before asv takes flight.

Thanks in advance for any help

**Comment by HaoZeke** [comment]
I think I understand the issue, which is that the `python` key doesn't override the environment resolved `python`. This is definitely a bug, both `conda` and `mamba` solvers should respect (and prioritize) the `pythons` configuration option over existing values (perhaps with a warning).

It would also be good (as suggested) to check for the expected `python` version, but that might be trickier since that is executed in `asv_runner` (which doesn't have environment level information).

**Comment by mattip** [comment]
> This is definitely a bug, both conda and mamba solvers should respect (and prioritize) the pythons configuration option

Does this work now?
