### ISSUE TITLE
ENH: support configuration in `pyproject.toml`

### ISSUE THREAD

**Issue by fangchenli** [airspeed-velocity/asv#1295]
We should support configuration in `pyproject.toml`.

**Comment by HaoZeke** [comment]
I'm interested in this, but a little confused, which configuration options are relevant to `asv` in particular? Do you mean to have the entire `config.json` moved into `pyproject.toml`?

**Comment by zacharyburnett** [comment]
It might be useful to read a `[tool.asv]` table in `pyproject.toml`, if present, but I do not think we should  remove the ability to have a standalone `asv.config.json`

some use cases (ones I use, at least) put benchmarks in their own dedicated repositories that don't have  `pyproject.toml` (or any package metadata for that matter)

**Comment by mattip** [comment]
The original poster did not comment. Closing. Please reopen with more information if it is still relevant.
