### ISSUE TITLE
`environment_type: mamba` doesn't pick up channels in `environment.yml`

### ISSUE THREAD

**Issue by akihironitta** [airspeed-velocity/asv#1301]
## Description of the Bug
When I use `mamba` with `environment.yml`, asv doesn't read channels specified in the environment file.

For example, if I have this environment file, it fails to install `pytorch-cuda` (of `nvidia` channel) and other things as asv cannot find them in the channels that asv recognises:
```
name: benchmark

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pytorch
  - pytorch-cuda=11.8
```

---

I'm using 5ab2d29.

---

## Alternatives
A workaround is to specify channels via `asv.conf.json`:

```json
    "conda_channels": ["pytorch", "nvidia", "conda-forge", "defaults"],
```

**Comment by HaoZeke** [comment]
Ah, this was a design decision, if `environment.yml` is specified as the environment file it should pick it up. That being said, creation from the `environment.yml` file was buggy, but is also fixed by #1303.
