### ISSUE TITLE
MAINT,TST: Update minimum requirements and tests

### ISSUE THREAD

**Issue by HaoZeke** [airspeed-velocity/asv#1318]
Python 3.7 is EOL. 3.8 would require significant rewrites to the test suite.

**Comment by mattip** [comment]
Can this be closed?

**Comment by HaoZeke** [comment]
We still have `requires-python >= 3.7` but I'll see if we can pin to `3.8`

**Comment by HaoZeke** [comment]
Easily fixed but upgrading isn't really useful at the moment.
