### ISSUE TITLE
asv 0.6.0 errors on environments with missing `packaging` module

### ISSUE THREAD

**Issue by moorepants** [airspeed-velocity/asv#1323]
SymPy's CI that runs asv is breaking (see https://github.com/sympy/sympy/issues/25561) with this error:

```
Run asv run --config asv.conf.actions.json
Couldn't load asv.plugins.mamba because
No module named 'mamba'
Couldn't load asv.plugins.virtualenv because
No module named 'packaging'
· Unknown environment type 'virtualenv'
· No environments selected
Error: Process completed with exit code 1.
```

I've looked through the change log and the diff of 0.6.0 to the last release and see that there is a new mamba plugin, but I haven't been able to see why these failures are occurring or if we are supposed to update something on our end to work with the new release. Can you provide a suggestion?

**Comment by Xemorr** [comment]
I am also experiencing this error

**Comment by HaoZeke** [comment]
> I am also experiencing this error

Could you post the full error?

**Comment by HaoZeke** [comment]
> SymPy's CI that runs asv is breaking (see [sympy/sympy#25561](https://github.com/sympy/sympy/issues/25561)) with this error:
> 
> ```
> Run asv run --config asv.conf.actions.json
> Couldn't load asv.plugins.mamba because
> No module named 'mamba'
> Couldn't load asv.plugins.virtualenv because
> No module named 'packaging'
> · Unknown environment type 'virtualenv'
> · No environments selected
> Error: Process completed with exit code 1.
> ```
> 
> I've looked through the change log and the diff of 0.6.0 to the last release and see that there is a new mamba plugin, but I haven't been able to see why these failures are occurring or if we are supposed to update something on our end to work with the new release. Can you provide a suggestion?

One of the possible environment management systems must be available. Although `mamba` may not be a worthwhile dependency in some situations, the `virtualenv` issue is that `packaging` is not present, and so it should be fixed by [adding it](https://pypi.org/project/packaging/) to the build environment.
