### ISSUE TITLE
Custom build commands

### ISSUE THREAD

**Issue by salotz** [airspeed-velocity/asv#1344]
I'm trying to run benchmarks for a Python project but one that does not use "standard" `pip install` compatible tooling (its a standalone application that is distributed by source and not python packages). I do use `pants` for builds which is not pip installable and it looks like during the `asv run` command I'm getting an error that the executable is not in the temporary venv dir.

It should be possible to use tools outside of that `PATH` and not only pip installable.

Is this already possible and I missed it, otherwise definitely a blocking feature for me.

**Comment by HaoZeke** [comment]
This is the relevant section of the [documentation regarding customizing the build process](https://asv.readthedocs.io/en/stable/asv.conf.json.html?#build-command-install-command-uninstall-command). Please reopen if there are `pants` specific bugs you run into! :)
