### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by Czaki** [airspeed-velocity/asv#1345]
The documentation on readthedocs is for avs 0.5.1, when the last release is 0.6.1

![obraz](https://github.com/airspeed-velocity/asv/assets/3826210/a066870a-f03e-4458-9858-0ae3abf1065d)

**Comment by mattip** [comment]
I don't understand how readthedocs picks its "stable" version. It seems the `v` in the version tag is confusing the algorithm?

**Comment by mattip** [comment]
I opened an issue in readthedocs https://github.com/readthedocs/readthedocs.org/issues/10782

**Comment by Czaki** [comment]
But current stable is 0.6.1, for which build do not exists even (there is 0.6.0, but no 0.6.1)

Check this tab https://readthedocs.org/projects/asv/versions/. In my other project, multiple versions are inactive, but I could enable them manually.

**Comment by mattip** [comment]
Fixed. There was a stale branch named "stable". I deleted it and now the docs are OK. Please refresh your browser when visiting the site.

Thanks for the report
