### ISSUE TITLE
Install instructions are a little confusing

### ISSUE THREAD

**Issue by travishathaway** [airspeed-velocity/asv#1352]
I am new to this project and was reading through the install instructions. I found them a little confusing because they mention install methods via `pip` but then go on to mention the `mamba` and `conda` CLI tools.

I have a couple questions for the maintainers:

- Are the install instructions trying to say, "if you are unable to install the dependencies via `pip`, you can attempt via `mamba/conda`?"

- Is there a need to create a set of install instructions specifically for `mamba/conda`?

I would be happy to help with the latter if that is the case. Otherwise, it would be nice to clarify why exactly you are recommending users install `mamba/conda`.

**Comment by mattip** [comment]
Could you point to where you are looking in the documentation?

When running benchmarks, ASV creates a virtual environment and installs packages, then runs the benchmarks inside that virtual environment. This allows reproducibility, and comparison of various versions of the package under test: each virtual environment can install a different version of the package, with perhaps different package dependencies.

ASV can use either virtualenv/pip, or conda/mamba to build the virtualenv. Sometimes one is easier to use than the other.

**Comment by HaoZeke** [comment]
Closing for now, please feel free to reopen if something else comes up.
