### ISSUE TITLE
BUG: "environment_type": "mamba" fails

### ISSUE THREAD

**Issue by jmccreight** [airspeed-velocity/asv#1353]
On both MacOs and Windows, I'm unable to use mamba (which is problematic since conda is timing out when run in asv on windows). On both I get the same error 

```
* Unknown environment type 'mamba'
* No environments selected
```

pip show indicates that I'm up-to-date with asv 0.6.1.

Maybe I'm missing something in my setup, but I've looked through the documentation as much as I can and dont see anything I find as germane. 

Thanks for your help.

**Comment by HaoZeke** [comment]
Is `libmamba` present? Could you provide some more information about how the rest of the environment is populated?

**Comment by jmccreight** [comment]
Hi,
Are you asking if libmamba is in my PATH? it is not. but "mamba" is as a
function.

I have been using mambaforge (which I see is now identical to miniforge as
of 9/2023 and specifically discouraged). If you have a suggestion for
installing mamba so that asv can use it, I'm open to it as I guess I'm
changing how I do things in the near future anyway.

thanks and happy new year!


-------------------------------------------------------
James L. McCreight
Research Hydrologist ~ Software Engineer
USGS Enterprise Capacity
UCAR CPAESS
cell:         831-261-5149

**Comment by jmccreight** [comment]
Hi again, 

I think the simple solution is just `conda install libmambapy` in the environment with asv. Seems obvious. But I had to understand more on the relationship of conda and mamba to before I knew what to do. 

I think that saying (in the installation instructions) that:
* [libmambapy](https://mamba.readthedocs.io/en/latest/python_api.html), which is typically part of mamba

is kind of misleading because, at least as far as I could tell, while libmamba and libmambapy are available in the base env, you can not (easily) access them for other environments. I also did not want to install asv into base (which is forbidden by mamba). I was getting hung up on expecting libmamba to be available like conda is, from any environment. But maybe I missed another option here? As far as my solution is concerned, its irrelevant that these ship with mamba because you need a separate installation anyway.

Of course, libmambapy is not on pip and so cant be included in the pyproject.toml as an optional dependency either. 

I'm still curious, how do you suggest making libmambapy available in non-base environments when using mamba? And I think it could be very helpful to mention this in the docs in one or two sentences.

Thanks!

**Comment by maximlt** [comment]
Have you tried running conda with the [conda-libmamba-solver](https://conda.github.io/conda-libmamba-solver/user-guide/), instead of mamba? This is now the new conda default solver.

**Comment by trexfeathers** [comment]
> Have you tried running conda with the [conda-libmamba-solver](https://conda.github.io/conda-libmamba-solver/user-guide/), instead of mamba? This is now the new conda default solver.

For me, this has been fine. However I'm aware that Mamba does still offer other benefits such as parallel downloads.

**Comment by maximlt** [comment]
conda performs parallel downloads since end of 2022 :) https://docs.conda.io/projects/conda/en/stable/release-notes.html#id69
