### ISSUE TITLE
ENH: Override default channels for `conda` / `mamba`

### ISSUE THREAD

**Issue by hmaarrfk** [airspeed-velocity/asv#1358]
In the mamba plugin, the conda-forge channel is added by default

https://github.com/airspeed-velocity/asv/blob/b8cbf81ccb808158102692a6fc42b8a9b2f2861e/asv/plugins/mamba.py#L59

I understand that this is convenient, but it seems to me that this "removes" choice from the end user's control.

I don't see why users should be required to have this channel enabled.

**Comment by HaoZeke** [comment]
We need a default channel to resolve dependencies from (this is also true of the `conda` plugin).

In principle a command line flag can be added to override the base channel, and such a PR would be welcome, but it might be a while for me personally to get to it.

**Comment by hmaarrfk** [comment]
Thank you for the quick and thoughtful reply.

I was somewhat stepping through the code to find out why i couldn't use the mamba backend:

I found that the context loaded by libmamba didn't have the users' `.condarc` loaded.
https://github.com/airspeed-velocity/asv/blob/master/asv/plugins/mamba.py#L76

I'm not super adept at the conda an libmamba python API so I can't really help.

The lack of the "context" felt like a different behavior compared to the conda backend.

**Comment by hmaarrfk** [comment]
I wanted to point you to some changes at mamba
https://github.com/mamba-org/mamba/issues/2357

This will likely make it hard to transition.

For the conda issue, I feel that it takes a totally different code path which just uses the `conda` commands instead of the `mamba` command.

I feel like for conda the lines could be removed (it may cause some discomfort downstream, but we could add warnings or documentation).

I noticed you changed the title to `conda / mamba` but I feel like the problems are distinct.

**Comment by HaoZeke** [comment]
> I noticed you changed the title to conda / mamba but I feel like the problems are distinct.

Ah I didn't read clearly enough. Yes the `context` loss is a `mamba` only issue (and is a bug), but the choice of default channel (and option to override) is a `conda / mamba` issue (and more an idea / discussion / enhancement).

**Comment by hmaarrfk** [comment]
I see I understand.

Thank you for dissecting the two.

**Comment by HaoZeke** [comment]
Just leaving some thoughts on the `mamba` context issue. The issue is that `libmambapy` doesn't actually have an easy API for handling `.condarc` or any of the `.rc` files. A limited fix could be testing for the `MAMBARC` environment variable and parsing it to override the channels, and set the `channel_priority`.

Would that cover your use case @hmaarrfk? The defaults (`conda-forge`) will then be ignored if `MAMBARC` is defined.**

** It is possible to try to follow the `.rc` file ordering `conda/mamba` use but this would make more sense from an `asv` scope IMO

**Comment by hmaarrfk** [comment]
would I use this like:
```
MAMBARC=${HOME}/.condarc asv ...
```
or an option in the ASV file?

I think that in general:

1. An environment variable or a configuration option would be great and definitely in line for the typical ASV usecase.
2. Following the ordering `conda/mamba` use was my expectation as an end user when I read "asv + mamba"


My use case is that we have a channel with some private packages so we have our dev environments configured to provide a token for the anaconda channel. Our development environments are already "working" with "mamba", so it was somewhat surprising that it was difficult to get them to work with "asv + mamba".

**Comment by HaoZeke** [comment]
> would I use this like:
> 
> ```
> MAMBARC=${HOME}/.condarc asv ...
> ```
> 
> or an option in the ASV file?
> 
> I think that in general:
> 
>     1. An environment variable or a configuration option would be great and definitely in line for the typical ASV usecase.
> 
>     2. Following the ordering `conda/mamba` use was my expectation as an end user when I read "asv + mamba"
> 
> 
> My use case is that we have a channel with some private packages so we have our dev environments configured to provide a token for the anaconda channel. Our development environments are already "working" with "mamba", so it was somewhat surprising that it was difficult to get them to work with "asv + mamba".

I've implemented (1) in #1373 (and removed `conda-forge` as a default), if it works then I'll consider this issue closed. The `.rc` following should ideally live in an externally managed `asv mamba` plugin IMO (if that ever happens).
