### ISSUE TITLE
CI Alerts

### ISSUE THREAD

**Issue by pkp124** [airspeed-velocity/asv#1360]
Hi,

I am new to ASV, and would like to know if there is possibility of sending alerts to pull requests if benchmarks fall below a certain threshold. Any guidance on this would be appreciated. 

Thanks.

**Comment by HaoZeke** [comment]
This would be out of scope for ASV. The solution would likely be to parse the output and use something like a CI script (maybe [with this](https://github.com/actions/github-script)) to trigger a webhook to deliver a alert or something.

If you come up with a workflow please feel free to open an update to the documentation with an example of it :)
