### ISSUE TITLE
Not able to set a benchmark class attribute to control the number of runs

### ISSUE THREAD

**Issue by MridulS** [airspeed-velocity/asv#1364]
I'm working on a benchmark which updates the data created by the `setup` function, and I want to make sure that the `time_` function is only run once between setup and teardown. The `number` benchmark attribute isn't respected when it's set in the following way:
``` python
class SomeBenchmarks:
    number = 1

    def setup(self):
        self.x = [1]
    
    def time_pop(self):
        self.x.pop()
```
It tries to run the benchmark twice and it errors out as it's trying to pop out from an empty list.

```
               IndexError: pop from empty list
               asv: benchmark failed (exit status 1)
```

Not sure if I am doing something wrong here.

**Comment by mattip** [comment]
You cannot do that. The essence of running benchmarks is that the `setup` function is called once, and then the `time*` function is called many times. The time to run "many times" is measured, and a single benchmark run's time is the average of those runs.
