### ISSUE TITLE
ENH: Provide feedback during "cloning project" stage

### ISSUE THREAD

**Issue by dstansby** [airspeed-velocity/asv#1365]
After running `asv run` for the first time, `· Cloning project` shows up in the terminal. It doesn't provide any feedback that it's donig anything though, and for large repositories it can take a while. It would be nice to show the output of `git clone`, which has a progress meter so the user has some feedback that something is happening and the clone isn't stuck.

**Comment by HaoZeke** [comment]
Isn't the output of `git` shown if `-vvv` is passed?

**Comment by HaoZeke** [comment]
Closing for now, please reopen with an MWE if `-vvv` isn't sufficient.
