### ISSUE TITLE
MAINT: Update default branch from master to main

### ISSUE THREAD

**Issue by dstansby** [airspeed-velocity/asv#1368]
Since 2020 GitHub has been using `main` for the default branch name. See https://github.com/github/renaming/ for more info. It would be good to update:

- The default branch name in this repository
- Any instances of `master` in the sample configuration and docs

**Comment by HaoZeke** [comment]
Thanks @dstansby. I'm ok with this, and have the permissions to do the needful, but I'll leave it till Monday, if there is no dissent then I'll go ahead :)

**Comment by HaoZeke** [comment]
Pinging some other maintainers with the commit bit as well, maybe @mattip, @fangchenli, @pv, @mdboom..

**Comment by HaoZeke** [comment]
Also @datapythonista :)

**Comment by mattip** [comment]
Seems like we should do this.

**Comment by fangchenli** [comment]
+ 1

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by HaoZeke** [comment]
Done, thanks all :)
