### ISSUE TITLE
BUG: `asv run` fails in GitHub Actions with `SpecNotFound: ...yml is not a valid yaml file.`

### ISSUE THREAD

**Issue by hameerabbasi** [airspeed-velocity/asv#1374]
Attached are the run logs (with `-v` turned on for easier debugging): 

[logs_5.zip](https://github.com/airspeed-velocity/asv/files/14125751/logs_5.zip)

[asv.conf.json](https://github.com/airspeed-velocity/asv/files/14125766/asv.conf.json)

The `environment_type` is `conda`.

**Comment by HaoZeke** [comment]
I see from the logs that this is for `asv` version `0.5.1`, could you try to re-run with the latest released ASV?

**Comment by HaoZeke** [comment]
Tentatively closing as not present on `main`.

**Comment by trexfeathers** [comment]
I think I had this one. Here is a description, and our solution:

https://github.com/SciTools/iris/issues/5280#issuecomment-1525802077
