### ISSUE TITLE
QUERY: `Unknown environment type 'mamba'`

### ISSUE THREAD

**Issue by lucascolley** [airspeed-velocity/asv#1390]
https://github.com/scipy/scipy/issues/20162#issuecomment-1974801706 @HaoZeke 

On running SciPy's benchmark suite I see `Unknown environment type 'mamba'. Allowed values based on existing plugins are ['existing', 'conda', 'virtualenv'].`.

Versions:
- `asv 0.6.3`
- `libmamba 1.5.6` 
- `libmambapy 1.5.6`
- `mamba 1.5.4`

All from conda-forge.

**Comment by HaoZeke** [comment]
Ah yes, so this needs `conda-build` as well now since `mamba_helpers` had to be vendored in, it used to be a dependency of the older versions of `libmamba`. Could you check if installing `conda-build` fixes this?

**Comment by HaoZeke** [comment]
I'll keep the issue open, we need clearer installation dependencies in the log.

**Comment by lucascolley** [comment]
> Could you check if installing conda-build fixes this?

Yep, that's it 👍
