### ISSUE TITLE
ASV Does not work with latest versions of conda

### ISSUE THREAD

**Issue by adam2392** [airspeed-velocity/asv#1412]
I am running the following ASV command and get the following error:

```
(sklearn) (base) adam2392@arm64-apple-darwin20 asv_benchmarks % asv setup --verbose 
Couldn't load asv.plugins._mamba_helpers because
No module named 'libmambapy'
· Creating environments
·· Creating conda environment for conda-py3.12-cython3.0.10-joblib1.3.2-numpy1.25.2-pandas2.1.0-scipy1.11.2-threadpoolctl3.2.0
·· Running '/Users/adam2392/miniforge3/bin/conda env create -f /var/folders/6_/sl83qtkd68x3_mvfys07_6qm0000gn/T/tmpcrx8xnai.yml -p /Users/adam2392/Documents/scikit-learn/asv_benchmarks/env/c6989ba2defdc48744a49c5e50663801 --force'
   OUTPUT -------->
   usage: conda [-h] [-v] [--no-plugins] [-V] COMMAND ...
   conda: error: unrecognized arguments: --force
```

```
(sklearn) (base) adam2392@arm64-apple-darwin20 asv_benchmarks % conda --version
conda 24.5.0
```

```
(sklearn) (base) adam2392@arm64-apple-darwin20 asv_benchmarks % asv --version
Couldn't load asv.plugins._mamba_helpers because
No module named 'libmambapy'
asv 0.6.3
```

An unrelated point, but I seem to be getting that the `libmambapy` is not found even though I have mamba installed.

**Comment by HaoZeke** [comment]
Closing as fixed in https://github.com/airspeed-velocity/asv/pull/1403/

(not released yet though)

Also for `libmambapy` see https://github.com/airspeed-velocity/asv/issues/1390#issuecomment-1974834097

**Comment by flying-sheep** [comment]
when will this be released?

**Comment by nawtrey** [comment]
I came here to report the same thing. I spent a while chasing issues, and eventually came across https://github.com/conda/conda/issues/13704. After downgrading my `conda` version to the last version that supports `--force` (i.e. using `conda install conda=24.1.2`) I was able to run `asv check` successfully.
