### ISSUE TITLE
QUERY: "Change" column not populated when running `asv compare`

### ISSUE THREAD

**Issue by philipc2** [airspeed-velocity/asv#1414]
Is the "Change" column supposed to be blank when running `asv compare`? I was under the impression that this would include the difference in the benchmark values between the two results. 

Below is a screenshot of a couple entries from when I ran `asv compare`. 

![image](https://github.com/airspeed-velocity/asv/assets/67855069/13f429d6-219a-427f-9aed-8b0b6b3a383f)

Here is the full output: https://github.com/UXARRAY/uxarray/pull/831#issuecomment-2201583704

**Comment by HaoZeke** [comment]
I think this is also fixed by #1421, but it might be a few days before that's released

**Comment by philipc2** [comment]
@HaoZeke 

That makes sense! I was expecting it to show the difference between the Before & After, but with #1421 the documentation improvements should make it much more clear!

Thank you for the clarification!
