### ISSUE TITLE
JSONC support is bugged

### ISSUE THREAD

**Issue by lucascolley** [airspeed-velocity/asv#1425]
@HaoZeke there was an oversight in my PR - the default is actually defined at the level of the command as well as in `config.py`:

https://github.com/airspeed-velocity/asv/blob/bc2d07e8fab8926706e9d8ee7bf506dea6479b41/asv/commands/common_args.py#L26-L29

I think we should make it so that the command defaults to `None`, and let `config.py` handle the `None`?

**Comment by HaoZeke** [comment]
> @HaoZeke there was an oversight in my PR - the default is actually defined at the level of the command as well as in `config.py`:
> 
> https://github.com/airspeed-velocity/asv/blob/bc2d07e8fab8926706e9d8ee7bf506dea6479b41/asv/commands/common_args.py#L26-L29
> 
> I think we should make it so that the command defaults to `None`, and let `config.py` handle the `None`?

Sure that makes sense. Sorry I didn't catch it in the review.
