### ISSUE TITLE
`asv dev` section still present in documentation after deprecation 

### ISSUE THREAD

**Issue by philipc2** [airspeed-velocity/asv#1427]
The section for `asv dev` in the commands section is still present and hasn't been updated even though this feature has been deprecated. 

https://asv.readthedocs.io/en/stable/commands.html#asv-dev

Should this section be removed, or would it be better to add a warning (such as what NumPy does)

https://numpy.org/doc/1.25/reference/generated/numpy.find_common_type.html

![image](https://github.com/user-attachments/assets/1dc93699-6a85-4a78-a9fa-a524ff8df39e)

Could include the following (taken from the RunetimeError when running `asv dev`

> asv dev has been removed. It was a shortcut of `asv run`, which you can use instead. It was removed because it caused confusion, in particular after changing what it was running in asv 0.5.x
> 
> You can be interested in the next `asv run` arguments:
>  - `--python=same`: to use the current environment and not create one
>  - `--quick`: to run benchmarks just once
>  - `--dry-run`: to not save the results

**Comment by HaoZeke** [comment]
I think for ASV it would be easiest to simply remove it from the current documentation. Earlier versions will have the older documentation and it isn't relevant anymore since we raise errors now. In NumPy the deprecation in the docs is tied to a warning being issued in the code AFAIK.
