### ISSUE TITLE
Support pyproject.toml

### ISSUE THREAD

**Issue by peekxc** [airspeed-velocity/asv#1435]
You should add configuration ability of the `asv.conv.json` via `pyproject.toml`. It what its meant for. Learn from the [JS world](https://gabri.me/blog/death-by-thousand-config-files)... avoiding *yet another top-level config file* is always preferred.

**Comment by HaoZeke** [comment]
Thanks, but AFAIK `asv` predates the inclusion of package specific tables (and `pyproject.toml` files itself) by several releases. Also, most projects which use `asv` have separate repositories for running the benchmarks, e.g. https://github.com/HaoZeke/asv-numpy

So there isn't too many places where I anticipate this being of use. However, it is annoying to have it in `json`, so perhaps as a side effect of #915, this might be in.

For now I'm closing this as unplanned, but a PR is welcome.
