### ISSUE TITLE
Matrix for environment variables

### ISSUE THREAD

**Issue by snorfalorpagus** [airspeed-velocity/asv#165]
Is there an existing feature for managing environment variables in a similar way to module dependencies?

For example, I'd like to run my benchmarks `WITH_FOO=1` and `WITH_FOO=0`, then have the benchmarks call a function with this as an argument, e.g.:

```
if os.environ['WITH_FOO'] == '1':
    # do something
else:
    # do something else

def time_something():
    # usual benchmark stuff
```

The purpose of this is that the [Shapely](https://github.com/Toblerity/Shapely) module has an optional "speedups" module that uses compiled cython instead of ctypes. The changes are global (i.e. many functions benefit from the speedups module), and I'd like to be able to benchmark with and without them, without having to duplicate a lot of code.

**Comment by mdboom** [comment]
There isn't currently a way to do this, but it's a very good idea.  I'd definitely accept a patch, and if I find the time for this, I'll self-assign first.

**Comment by yarikoptic** [comment]
I would love to see this feature implemented too!  My endless kudos to the one who implements it ;)
In our case we would love to benchmark @datalad under different default versions of git-annex repositories.

**Comment by marmoute** [comment]
We would also be happy to have this kind of feature ☺
