### ISSUE TITLE
Benchmark discovery project version suboptimal

### ISSUE THREAD

**Issue by pv** [airspeed-velocity/asv#208]
The benchmark discovery seems to be run currently against whatever version was last active.
This is sometimes sub-optimal:
- Benchmarks may have imports written for the current project version, which fail for earlier version
- If the last version happens to result to build failure, all following asv operations will just fail

Perhaps best would be to give a config option that determines this, or just always check out master branch first.

**Comment by mdboom** [comment]
This was done to be fast about discovering benchmarks, though with ccache and wheel cache support (almost) in place it's now less of an issue, and I think always checking out master will be the right thing in the majority of cases.

At the end of the day, though, benchmarks need to be written to be importable across all versions of the underlying project's API, and if there's a project commit in which the benchmarks fail to import, the benchmarks haven't been written correctly.  So we should probably:

- Handle ImportError during the importing of the benchmark suite when a benchmark is about to be run as a bigger error than just a "failed test" to flag that the benchmark suite probably needs some tweaking.

- Add a documentation note about that on the "writing benchmarks" page that the benchmark suite should be importable across API versions of the underlying project, and some strategies for that.

**Comment by pv** [comment]
#568 should address this.
