### ISSUE TITLE
Tests failing when shelling out to conda

### ISSUE THREAD

**Issue by anderspitman** [airspeed-velocity/asv#270]
When running `python setup.py test` I'm getting the following error when running in a fresh conda environment:

```
[604.17%] ··· Error running /home/anders/anaconda/envs/asv-test/bin/conda create --yes -p /tmp/pytest-0/test_run_new_all0/env/51ea1b41623d668554f676f8b747c3c1 --use-index-cache python=2.7 pip
```

If I run that command manually:

```
 /home/anders/anaconda/envs/asv-test/bin/conda create --yes -p /tmp/pytest-0/test_run_new_all0/env/51ea1b41623d668554f676f8b747c3c1 --use-index-cache python=2.7 pip
```

It seems to create the env just fine. Wondering if anyone else is having this issue or if it's just something wrong with my setup.

**Comment by pv** [comment]
Please give the whole error message --- anaconda will probably print out
a reason why it failed.

**Comment by anderspitman** [comment]
Hm I am unable to reproduce the problem today. I must have been doing something weird. Sorry!

**Comment by pv** [comment]
Note that the failure may be real but sporadic, e.g. too busy Anacoda package servers or other connection problems.

Another possibility is a race condition inside conda --- some of the tests exercise parallel environment creation. If multiple environment creation commands are launched simultaneously, and conda needs to use some internal caches, *and* their locking is not properly implemented in the  `conda` command, then some random-looking problems will probably crop up. I don't know anything about internals of `conda`, however, so I don't know if this is the case. The error messages it prints might tell something about this.

**Comment by anderspitman** [comment]
Thanks, I'll keep that in mind. I didn't save the full message. If I see it again I'll post it.
