### ISSUE TITLE
Documentation on how to set up a good test machine

### ISSUE THREAD

**Issue by asmeurer** [airspeed-velocity/asv#292]
I hope you don't mind me opening this issue here. I would send this to a mailing list, but I didn't see one for asv. I was wondering if you had any or would be willing to add any documentation on how to set up a good test machine, and common pitfalls and so on to avoid?

We would like to be using asv for SymPy (see https://groups.google.com/forum/#!topic/sympy/UV_2_2RXuTY). A suggestion was made to use a Raspberry Pi 2 as a consistent hardware set. It seems like a good option both because they are really cheap, and because they have uniform hardware, meaning we could potentially get new or redundant hardware and still have comparable benchmarks. Has anyone done this before? Is the hardware reliable enough (and promised to be consistent in the future) that you can reasonably compare benchmarks run on different machines? Are there other pitfalls to be aware of?

**Comment by mdboom** [comment]
My testing rig for astropy is a 2014 Mac Mini.  Even though it's a multicore machine, I try really hard to make sure nothing else is running while running the benchmarks.  To that end, I have a cronjob that reboots it every day at 1am, and then runs the benchmarks at 2am.  (The reboot may be overkill, but it makes sure anything I may have been doing on it that day isn't resident and affecting the results).  A headless Linux box would probably be better, as it is likely to have fewer daemons running etc., but that's the hardware I happened to already have to use for this purpose.

Raspberry Pi is an interesting idea.  Obviously there will be some differences (smaller caches, weaker FPU etc.) that make it perform differently than an x86 PC.  But for catching large relative regressions, it may still be useful.  And the other nice thing is you can probably afford to have more than one.  I'd say go for it and report back about your experience.

(Anecdotally, I used to run a Raspberry Pi B+ (1st gen) for a while and didn't find it to be terribly reliable -- it would randomly reboot and often damage the SD card filesystem in the process.  My understanding is that the Pi 2 is much better in this regard though.)

**Comment by asmeurer** [comment]
Do you have any suggestions/documentation/examples on how to setup a headless server (setting up github keys, deploying the results, making sure things are reasonably secure against malicious code)?

**Comment by pv** [comment]
FWIW, in case you are wondering how useful a "pessimal configuration" of
a VM on a desktop machine that's not idle is, the current Scipy results
are produced on such platform, https://pv.github.io/scipy-bench/
Depending on the benchmark, it's fairly noisy, but the long-term
performance changes remain for the most part visible.
.
Regarding security --- I'm using a separate results repository (eg.
symlinking results/) and [github deployment
keys](https://developer.github.com/guides/managing-deploy-keys/#deploy-keys)
that give push permissions only to it. As the benchmarks are in the main
repository, this is a must, but a separate results repository may be
useful even if your benchmarks are in a repo of their own already.
.
If you are using a VM or container environments, you can isolate running
the benchmarks (cf https://github.com/pv/scipy-bench-setup) from the
deploy keys; at least it requires an attacker to use more advanced
attacks to do harm. The vectors for injecting malicious code are via Pip
and the github code repositories. If either of these gets compromised,
you likely already have more urgent problems than a compromised
benchmark machine.
.
Can't comment on RPi2 --- it probably can't run VMs, but containers
probably are available.

**Comment by pv** [comment]
Maybe just a comment that the current numpy/scipy benchmarks run on the cheapest Atom processor dedicated server I could find, which is mainly good enough (apart from some performance differences due to CPU cache etc. to more top-of-the-line processors), for ~60 €/year. I'd generally recommend dedicated machines over AWS etc. instances, both from load and cost perspectives.

**Comment by prisae** [comment]
@pv, would you mind sharing your server instructions how to run `asv` in an automated fashion on a daily basis on a server and push new results? I assume you use cronjobs?

This would help tremendous to less server-savvy people like me to set-up automated benchmarks. Thanks!

**Comment by pv** [comment]
It's here:
https://github.com/pv/scipy-bench-setup
https://github.com/pv/asv-bwrap

**Comment by prisae** [comment]
Great, thanks for the links!
