### ISSUE TITLE
Consider using dill instead of pickle for setup_cache

### ISSUE THREAD

**Issue by yoavram** [airspeed-velocity/asv#347]
From the [Dill pypi page](https://pypi.python.org/pypi/dill):

> Dill extends python’s ‘pickle’ module for serializing and de-serializing python objects to the majority of the built-in python types.
> So dill is useful if the data-types generated in `setup_cache` are not supported by pickle.

I think that this change only requires adding dill as a dependency and then replacing `import pickle` by `import dill as pickle`.

**Comment by mdboom** [comment]
:+1:  This can even be a optional, so as to not introduce a new non-stdlib dependency.

**Comment by yoavram** [comment]
Yes, but then maybe do something like:
```
try:
    import dill as pickle
except ImportError
    import pickle
```
One benefit of dill is that it allows `setup_cache` to calculate objects that have lambda functions as members.

**Comment by HaoZeke** [comment]
Closing as not needed. None of the equivalents are as universal as `pickle`, #1275 has more information on the rationale.
