### ISSUE TITLE
Feature request: preserve start/end date of run in results

### ISSUE THREAD

**Issue by astrofrog** [airspeed-velocity/asv#379]
In some cases, for example if a server has a known issue in a certain date range, it would be nice to be able to know which result files to remove. Of course, the modification date of the json file provides this, but it would be nice to have a more formalized way of keeping this information in the `json` files.

**Comment by mdboom** [comment]
Seems like a good idea.  I'll write up a pull request.

**Comment by pv** [comment]
was in #428
