### ISSUE TITLE
BUG: Issue with conda PREFIX length

### ISSUE THREAD

**Issue by astrofrog** [airspeed-velocity/asv#382]
This is an issue that was originally reported in https://github.com/spacetelescope/asv/issues/169 and should have been fixed in https://github.com/spacetelescope/asv/pull/181 - but for some reason, I am still seeing this issue when running `py.test test/`:

```
[1883.33%] ······ No `environment_type` specified in asv.conf.json. This will be required in the future.
[1883.33%] ······ No `environment_type` specified in asv.conf.json. This will be required in the future.
[1883.33%] ······ No `environment_type` specified in asv.conf.json. This will be required in the future.
[1883.33%] ······ Creating environments
[1883.33%] ······· Error running /Users/tom/miniconda3/bin/conda create --yes -p /private/var/folders/zy/t1l3sx310d3d6p0kyxqzlrnr0000gr/T/pytest-of-tom/pytest-69/test_run_new_all0/env/ab66d02784ae61b399d9c0df50dc4a77 --use-index-cache python=3.5 pip
                  STDOUT -------->
                  Fetching package metadata: ....
                  Solving package specifications: ...........

                  Package plan for installation in environment /private/var/folders/zy/t1l3sx310d3d6p0kyxqzlrnr0000gr/T/pytest-of-tom/pytest-69/test_run_new_all0/env/ab66d02784ae61b399d9c0df50dc4a77:

                  The following NEW packages will be INSTALLED:

                      openssl:    1.0.2g-0     
                      pip:        8.0.3-py35_0 
                      python:     3.5.1-0      
                      readline:   6.2-2        
                      setuptools: 20.1.1-py35_0
                      sqlite:     3.9.2-0      
                      tk:         8.5.18-0     
                      wheel:      0.29.0-py35_0
                      xz:         5.0.5-1      
                      zlib:       1.2.8-0      

                  Linking packages ...
[openssl             ]|                                                  |   0%            |   0%
                  STDERR -------->
                  Error: PREFIX too long: 135 characters, but only 128 allowed
                  Error: Error: post-link failed for: openssl-1.0.2g-0

[1883.33%] ······· Failure creating environment for py3.5-colorama0.3.1-six
```

Is this a regression? Or a slightly different issue?

**Comment by astrofrog** [comment]
A workaround for now is to specify the base temporary directory manually:

```
py.test --basetemp=/tmp/asv test
```

**Comment by pv** [comment]
Somewhat different issue (the temporary directory names are long on OSX), but probably the same cause. I don't know what the issue actually is --- why is there a 128 path name length limit somewhere in conda?

I'm not sure if there is a solution to this, you probably run into this if you do anything that involves creating a conda enviroment in a deep directory path.

**Comment by astrofrog** [comment]
Yes, I think this is just the result of the pytest generated path being too long on Mac, and the only workaround I found is to run the tests with ``--basetemp``. In that sense, maybe we can just close the issue since it's nothing asv can fix?

**Comment by wrwrwr** [comment]
Conda limits the prefix length as it wants to [substitute install for build paths](http://conda.pydata.org/docs/building/meta-yaml.html#making-packages-relocatable) in binary files without changing offsets. This may no longer be an issue as the current [openssl feedstock](https://github.com/conda-forge/openssl-feedstock) does not have the post-link script -- it relies on conda-build to do the prefix replacement and the latter should handle paths [up to 255 bytes](https://github.com/conda/conda-build/blob/master/conda_build/config.py#L26).

**Comment by pv** [comment]
Closing, I think this is not fixable in asv, and the conda change probably makes it a bit better. The environment paths are not exceptionally long ("env/sha1hash"), and in the case above the length is due to OSX+pytest.
