### ISSUE TITLE
Specifying conda channels in ``matrix``?

### ISSUE THREAD

**Issue by cgranade** [airspeed-velocity/asv#405]
Is it possible to specify a `conda` channel other than the default in the `matrix` key of `asv.conf.json`? I'm benchmarking a project which depends on CVXOPT, which suggests installing using `conda install -c https://conda.anaconda.org/omnia cvxopt`. Thanks!

**Comment by anirban89** [comment]
👍 this would be useful for our project [pyqg](https://github.com/pyqg/pyqg) as well

**Comment by pv** [comment]
Was implemented #539
