### ISSUE TITLE
Using asv programmatically

### ISSUE THREAD

**Issue by anderspitman** [airspeed-velocity/asv#413]
We're using asv in [autobencher](https://github.com/anderspitman/autobencher) with GitHub webhooks to automatically run benchmarks for each PR for [scikit-bio](https://github.com/biocore/scikit-bio). You can see an example by looking at the checks (like Travis) for any of the scikit-bio PRs. Currently I'm shelling out all the asv calls, but eventually it would be nice to import asv directly. The most immediate need is to hook into asv's regression detection, since what we really want for scikit-bio is for PR checks to fail and flag if a serious regression is detected.

Before diving into this myself I wanted to check with you all and see what your thoughts were:
1. How easy would asv be to use programmatically?
2. Is there a straight-forward way to hook into the regression functionality of asv, either by importing or shelling out?

Thanks for your input and thanks for making asv; it's awesome!

**Comment by pv** [comment]
Quick (probably incomplete) answer:
.
1. Possible, but I don't think there are guarantees about API stability
at this point. You can look under asv/commands if you mean the internal
plumbing or in test/tools.py if you mean calling main().
.
2. asv.step_detect is self-contained and operates on time series.

**Comment by anderspitman** [comment]
Thanks @pv. I'll take a look.

**Comment by anderspitman** [comment]
@pv is there anything special I need to do to force a regression? I tried using a `for` loop to artificially increase the runtime of one of the benchmarks, and the increased time shows up in the plot, but I don't see anything on the regressions page. I know the stats is fairly involved.
