### ISSUE TITLE
Uninstalling uses project name from setup.py, no package name autodetection

### ISSUE THREAD

**Issue by anderspitman** [airspeed-velocity/asv#416]
I must be missing something, but I haven't been able to track down the problem yet. Given the following config and benchmarks files pointed at a [dummy project](https://github.com/anderspitman/autobencher-test2) I'm using for testing:

``` json
{
    "version": 1,
    "project": "project",
    "project_url": "http://project-homepage.org/",
    "repo": "https://github.com/anderspitman/autobencher-test2.git",
    "environment_type": "conda"
}
```

``` python
from abtest import func1, func2, func3

class TimeSuite:
    def time_func1(self):
        func1()

    def time_func2(self):
        func2()

    def time_func3(self):
        func3()
```

I'm not seeing any difference in the benchmark times reported by asv between commits, even though I know there are regressions I've introduced. If I switch to a given commit, `pip uninstall`/`pip install` and run `%timeit` manually, it works as expected, but asv isn't picking it up. Any ideas?

**Comment by anderspitman** [comment]
Got it! When asv [does the `pip uninstall`](https://github.com/spacetelescope/asv/blob/1acf9612abc37ec993f62536b94673a08c2cc5cc/asv/environment.py#L505), it uses the project name from `asv.conf.json`, regardless of what the project is called in `setup.py`. Is there a reason asv needs the project name in the config and can't simply infer it from `setup.py`?

**Comment by njsmith** [comment]
Tryign to infer things from setup.py is kinda terrible since it's arbitrary code, but one could use `pip wheel` to run the setup.py and generate a nice static installable artifact with metadata.

**Comment by pv** [comment]
The uninstall command is customizable in #699, which probably is sufficient to close this.
Autodetection from wheel could be nice, but not sure if the complexity is worth it.
