### ISSUE TITLE
Return non-zero status code if there are any failures

### ISSUE THREAD

**Issue by astrofrog** [airspeed-velocity/asv#449]
For the [astropy-benchmarks](https://github.com/astropy/astropy-benchmarks), I would like the Travis status to be a failure if there are any failures during the benchmarks (currently there are three benchmark failures but Travis passes). Maybe a flag could be added to this effect?

**Comment by bjodah** [comment]
For [sympy_benchmarks](https://github.com/sympy/sympy_benchmarks), we would also be interested in a `asv --strict` flag or something along those lines. But in that case we would also like to be able to mark some legacy benchmarks as allowed failures, e.g. along the lines of:
```
@asv.mark.may_fail
def time_some_old_method():
    ...
```

**Comment by pitrou** [comment]
This would indeed be nice to ensure that benchmarks don't get stale because of changes in program code.
