### ISSUE TITLE
RFC: benchmark decorator

### ISSUE THREAD

**Issue by philpep** [airspeed-velocity/asv#482]
I think it could be more pythonic to handle benchmark attributes (params, setup etc) through a single decorator, this way it's more explicit to understand that arguments are injected in the function.

eg:

```
@asv.benchmark(params={'foo': ['bar', 'baz']}, type='time')
def mybench(self, foo):
    [...]
```

But I guess we don't have asv installed in the virtualenv used during benchmark and injecting the decorator while loading the module isn't explicit too.

**Comment by pv** [comment]
I agree that a decorator is a nicer way to do it.

I think a problem (or inelegancy) here is in exposing the `asvtools` module that contains the decorator. The decorator itself is also 6 lines of code, so if it's the only thing that would be there one can ask is it worth the trouble.  Such asvtools module was thought of at some point earlier: #182

**Comment by shoyer** [comment]
Maybe a recipe for such a decorator could simply be added to the ASV docs? I'd be happy to copy it into my project, but it would be nice not to have to think too hard about the design :).

I suppose the canonical implementation is something like:
```
def parameterized(names, params):
    def decorator(func):
        func.param_names = names
        func.params = params
        return func
    return decorator
```
(only 5 lines, not 6!)

**Comment by soupault** [comment]
Looking at http://asv.readthedocs.io/en/latest/writing_benchmarks.html, I've just come across the same idea. Sticking to method names is not quite Pythonic and, potentially, error-prone. :+1:

**Comment by HaoZeke** [comment]
Closing as completed in https://github.com/airspeed-velocity/asv_runner/pull/18 (and discussed a bit more in https://github.com/airspeed-velocity/asv/issues/1266).
