### ISSUE TITLE
Mangled output on windows

### ISSUE THREAD

**Issue by eric-wieser** [airspeed-velocity/asv#507]
Something is going wrong with the ascii-art for me on Windows 10:

![image](https://cloud.githubusercontent.com/assets/425260/24933980/1929752a-1f11-11e7-90b9-7408705647c9.png)

**Comment by pv** [comment]
Haven't been able to reproduce this on win10.

**Comment by eric-wieser** [comment]
It's possible I was running this in WSL. Sorry for not giving more info here. Feel free to close - it's minor at best, and I can always reopen if I see this next time I try it, along with more information when I do.
