### ISSUE TITLE
Detecting which repetition we're on

### ISSUE THREAD

**Issue by Warbo** [airspeed-velocity/asv#533]
I've got some benchmarks which I'd like to run repeatedly (e.g. 30 times), but with a different input on each repetition (taken from a deterministic data generator). Is there any way for the setup or benchmark function to "know" which iteration it's on, so I can select that input? I know I can parameterise, but that would separate the measurements and I'd lose the statistics.

There's no mention of this in the documentation, and I'm a little unclear about what is/isn't run in the same process, whether there's a deterministic order, etc. Could I, for example, put my benchmarks in a class, and increment a property like `self.foo_rep` each time `time_foo` is called? Would I be better off with module (global) variables?

Thanks

**Comment by pv** [comment]
You can set `self.counter = 0` in `__init__` and `self.counter += 1` in setup, and set `repeat = the_number_of_steps_you_want`. The repeats run in the same process.
https://asv.readthedocs.io/en/stable/writing_benchmarks.html#timing
