### ISSUE TITLE
Run asv for single commit

### ISSUE THREAD

**Issue by astrofrog** [airspeed-velocity/asv#544]
I am trying to run asv for a single commit but it seems to pick up all commits since the start of the project:

```
$ asv run --bench CsvFloat c2ef85974c13cbba5dc72df72607ff284cffc6d5
· Creating environments
· Discovering benchmarks
·· Uninstalling from conda-py2.7-Cython-jinja2-nomkl-numpy1.12-scipy
·· Building for conda-py2.7-Cython-jinja2-nomkl-numpy1.12-scipy..............
·· Installing into conda-py2.7-Cython-jinja2-nomkl-numpy1.12-scipy..
· Running 7996 total benchmarks (3998 commits * 1 environments * 2 benchmarks)
[  0.00%] · For astropy commit hash c2ef8597:
```

Is there a way to run single commits?

**Comment by pv** [comment]
Same as for "git log":
c2ef85974c13cbba5dc72df72607ff284cffc6d5^!

**Comment by astrofrog** [comment]
I wonder if we could add that example to the ``asv run`` help? This is some git-fu that not everyone will necessarily know.

**Comment by pv** [comment]
Yes, adding example somewhere, documentation, and maybe add in `asv run --help` something like following:

```
Run a benchmark suite.

examples:
  asv run master^!      run benchmarks for one commit (in git repository)
```
