### ISSUE TITLE
setting machine info doesn't work with Git Bash

### ISSUE THREAD

**Issue by rgommers** [airspeed-velocity/asv#546]
With asv 0.2, for all of ``asv`` ``dev/run/machine`` the output when run from Git Bash on Windows 10 is:

    $ asv dev
    ▒ No information stored about machine 'C25302'. I know about nothing.

    ▒ Run asv at the console the first time to generate one.

It does work in PowerShell, and on Git Bash it can be worked around with:

    $ winpty asv dev

The [if not sys.stdout.isatty():](https://github.com/spacetelescope/asv/blob/011815d287456efee0a24a9efe5a2c0c49b720f2/asv/machine.py#L151) check seems overly strict.

**Comment by pv** [comment]
Iirc even python shell doesn't work properly without winpty, so I think the
environment in question is non-standard insofar as python io is concerned.

21.9.2017 22.45 "Ralf Gommers" <notifications@github.com> kirjoitti:

**Comment by pv** [comment]
I think this is a wontfix, git bash does not provide interactive console input.
It's possible to use `asv machine` (also with `--yes` in future asv versions) to generate a config file with default values.

**Comment by rgommers** [comment]
It indeed doesn't work with the Python interpreter, but does work with IPython:

```
In [1]: import sys

In [2]: sys.stdout
Out[2]: <colorama.ansitowin32.StreamWrapper at 0x1b3a43b7e80>

In [3]: sys.stdout.isatty()
Out[3]: True
```

Given that Git Bash is probably the single most popular shell on Windows, I'd say it wouldn't hurt to at least fix the error message that is displayed so people don't lose time hunting for the ``winpty`` workaround.

**Comment by pv** [comment]
The message changed in 1108957f59a0773d59ea5a4fc4ca381b2d47cff0 to say to run `asv machine`

**Comment by pv** [comment]
Maybe the `colorama` console io fix that ipython has can be reused though since we're anyway using that library.
