### ISSUE TITLE
Cannot specify an install command (or no install)

### ISSUE THREAD

**Issue by rgommers** [airspeed-velocity/asv#547]
I'm writing benchmarks for a package that's not its own git repo, but is located in a subdir of a larger repo (I know, not optimal - can't control that in this case). There seems to be no way to specify the location of ``setup.py`` or a custom install command in ``asv.conf.json``, it assumes that the ``setup.py`` (or ``pyproject.toml`` etc.) is located in the root of the repo.

A more limited alternative that would also be useful is to just run the benchmarks in-place, without trying to clone, build a wheel, etc. Just execute benchmarks as is, giving responsibility for installing the package to the developer. 

The most similar issue I could find is gh-26 (custom install command), but either a ``--no-install`` or a ``--setup-file-location`` option seems more limited in scope and easier to implement than gh-26.

**Comment by tylerjereddy** [comment]
The ability to specify the `setup.py` path would indeed be useful. We closed my [original attempt](https://github.com/airspeed-velocity/asv/pull/535) at this because it was far too crude (although that is what our fork of asv is doing at the moment).
