### ISSUE TITLE
Move this to Astropy project?

### ISSUE THREAD

**Issue by pllim** [airspeed-velocity/asv#558]
We no longer have a maintainer for this at STScI. Since this is used heavily by Astropy, why not?

c/c @perrygreenfield @pv @astrofrog

**Comment by astrofrog** [comment]
Is this used by astropy more than other projects though? What about just making a dedicated asv organization?

**Comment by pv** [comment]
I don't think asv is at the moment closely associated with a specific
existing project.

So if it has to move, I think it either should be in a new github org,
or one of the lead devs adopts it as a personal project. A new org
sounds easiest ("asv" is taken, but "asv-dev" is free).

**Comment by astrofrog** [comment]
What about airspeed-velocity as the org name?

**Comment by pllim** [comment]
👍 to its own org

**Comment by pv** [comment]
Project moved to a separate org.

**Comment by pllim** [comment]
Thank you for handling this, @pv.
