### ISSUE TITLE
Quick still runs all of the warmups

### ISSUE THREAD

**Issue by ezyang** [airspeed-velocity/asv#559]
I would expect `--quick` mode to skip warm-up, but it doesn't. I think the problem is `warmup_time` is not being adjusted at this line: https://github.com/spacetelescope/asv/blob/master/asv/benchmark.py#L779

**Comment by pv** [comment]
This was partly intentional --- 0.1sec of warmup is small compared to the time it takes to launch the benchmarking subprocess, and not including it caused reported timings to be almost meaningless.

**Comment by ezyang** [comment]
I thought the point of quick was to help you test functional correctness, rather than actually do timings?

**Comment by pv** [comment]
Right, but in practice, removing the warmup probably doesn't gain you much speed increase for that.

**Comment by pv** [comment]
Changed anyway to 0 in #647
