### ISSUE TITLE
Would like a way to run commits only on merge commits

### ISSUE THREAD

**Issue by moorepants** [airspeed-velocity/asv#561]
Hi, we use asv for sympy and we do not have strict rules about combining all commits in a PR into one before merging, so SymPy has lots of commits that don't' really need to be benchmarked. It would be nice if there was an easy way to just run the benchmarks on the merge commits so we could essentially benchmark the result of each pull request. Is this something that is easy to do? If not, it'd be a nice feature to have.

**Comment by pv** [comment]
A work-around is to list commits one by one, along the lines of
"for c in `git log --merges --oneline --format=%H`; do asv run "$c^!";
done"

**Comment by moorepants** [comment]
Cool, that works. It probably wouldn't be too hard to make this work:

```
git log --merges --oneline --format=%H | asv run
```

**Comment by pv** [comment]
`asv run "--merges master"` works
