### ISSUE TITLE
Any way to use tuple params?

### ISSUE THREAD

**Issue by ColCarroll** [airspeed-velocity/asv#564]
I see [here](http://asv.readthedocs.io/en/latest/writing_benchmarks.html#parameterized-benchmarks) that you can have one or multiple params, I cannot figure out how to make something like
```
time_foo.params = (
    ('a', 1),
    ('a', 2),
    ('b', 1),
    ('c', 1)
)
```
work (i.e., I do not want the full product of two params).  The current implementation treats this as 4 params with two options each, and all combinations of them are passed in.

Is there any way to do the above currently?

**Comment by pv** [comment]
Pass the tuples in as a single parameter:
```
class SomeBenchmark(object):
    params = [[('a', 1), ('b', 2)]]
    def time_foo(self, arg):
        foo, bar = arg
```
