### ISSUE TITLE
Don't wait until benchmark is finished to show contents of standard error

### ISSUE THREAD

**Issue by Warbo** [airspeed-velocity/asv#566]
Stderr can contain information that the user might want to see *during* a particular benchmark run (an obvious example is a progress meter). Whilst asv does have an option to show the contents of stderr, it doesn't do so during the run; instead, it's gathered up and only displayed after that benchmark is finished.

It would be nice if stderr were given out as it's received, rather than waiting.

**Comment by HaoZeke** [comment]
Closed by https://github.com/airspeed-velocity/asv/pull/1262
