### ISSUE TITLE
Configuration file name and location

### ISSUE THREAD

**Issue by bwohlberg** [airspeed-velocity/asv#577]
The docs imply that the config file can be within the `benchmarks` directory

> For example, if the benchmarks are stored in the same repository as the project itself, and the configuration file is located at benchmarks/asv.conf.json inside the repository, you can set "repo": ".." to use the local repository.

but this doesn't actually seem to work: doing `asv run` from the project root directory leads to a `Config file ... not found` error, and running from the `benchmarks` directory leads to the error `No __init__.py file in 'benchmarks'`.

It would be useful if it were possible to put the config file at `benchmarks/asv.conf.json` to limit the clutter in the project root directory.

**Comment by pv** [comment]
See https://github.com/numpy/numpy/tree/master/benchmarks for an example.

**Comment by bwohlberg** [comment]
> See https://github.com/numpy/numpy/tree/master/benchmarks for an example.

Thanks. That structure works for me too.

> Of course that exerpt in the documentation is maybe somewhat misleading.

It wouldn't hurt to add a more detailed explanation.

> Does it work if you adjust the benchmark_`dir config` variable to `.`?

No, unfortunately not. I get the error ``No __init__.py file in './.asv'``. This would be my preferred directory layout if this error could be fixed.
