### ISSUE TITLE
Semi-Expensive Setup

### ISSUE THREAD

**Issue by jbrockmendel** [airspeed-velocity/asv#579]
If there is a more appropriate place for this like a mailing list, please let me know.

pandas uses asv to profile a bunch of things, some of which have the characteristic that a) the setup takes longer than the benchmark, and b) the setup does not take _long enough_ for `setup_cache` to be a game-changer.  Is there an option to run `setup` just once, kind of like `unittest.setup_class` vs `unittest.setup`?

**Comment by pv** [comment]
I think it's currently not possible to do better than `setup_cache` since each benchmark runs in a separate process.
