### ISSUE TITLE
Missing commit in published site

### ISSUE THREAD

**Issue by astrofrog** [airspeed-velocity/asv#587]
If I try and run ``asv publish`` in the following branch:

https://github.com/astropy/astropy-benchmarks/tree/results

the benchmarks run on the ``oneesk`` machine should have three commits, but only two are included in the generated site.

**Comment by pv** [comment]
Only commits occurring on the branches (in their linearized form) 
defined in the configuration file are included.

**Comment by astrofrog** [comment]
Ah I see now that one of the commits is not - thanks!
