### ISSUE TITLE
Feature Request: run with extra-large sample size

### ISSUE THREAD

**Issue by jbrockmendel** [airspeed-velocity/asv#588]
It would be nice to have a command line option that increases the number of iterations for each benchmark* to get extra-precise results.  Is something like this feasible?  If it's beginner-friendly, I'll be happy to make a PR.

\* Or runs each benchmark multiple times in randomized order to avoid contamination from background processes.

Context:  For reasons unknown, asv runs on my local machine have much higher variance than other pandas contributors.  I end up running asv several times to try to guess which results are "real".

**Comment by pv** [comment]
If you are on laptop, you are maybe seeing CPU turbo/frequency scaling. 
This can operate on long time scales, several seconds. If each 
measurement is longer than that, for big benchmark suite it can become 
impractical. An easier solution may be to look at fixing the clock 
frequency and turning off CPU turbo features (how to do that depends on 
the platform you are on).

**Comment by jbrockmendel** [comment]
I generally run these on an Ubuntu 16.04 desktop, have taken to running with `taskset` to reduce the variance a bit.  My local entropy field is mighty.

**Comment by pv** [comment]
PR for overriding benchmark parameters will be accepted.

How to do it could be to extend the "--quick" mechanism to 
"--override-param='target_time=20'". The parameters can be passed in to 
the runner process e.g. as a json-encoded dictionary on the command 
line. I have some code doing similar thing, I can push it somewhere 
online today evening if you want an example...

**Comment by jbrockmendel** [comment]
> I have some code doing similar thing, I can push it somewhere
online today evening if you want an example...

That would be great, thanks.  It would save me having to dig through the repo to find the appropriate places to tinker.

> How to do it could be to extend the "--quick" mechanism to
"--override-param='target_time=20'"

I'll give that a shot.  Longer-term would a better solution be to add another layer of looping to effectively run "asv foo bar baz" N times?  That seems like it would be more likely to smooth out background noise.

**Comment by pv** [comment]
I was thinking of this: 
https://github.com/pv/asv/commit/1fffb5bbd6d4bc1f8ad43fbcd5403068097229
c2
But now I see the extra_params stuff is nowhere near finished.

**Comment by pv** [comment]
The relevant command-line options were added in #647
