### ISSUE TITLE
Issue in --skip-existing behavior

### ISSUE THREAD

**Issue by astrofrog** [airspeed-velocity/asv#602]
I'm having an issue running tests for new configurations without re-running them for old configurations. Here is an example workflow:

- Set up the benchmarks and define only one Python/Numpy combination in ``asv.conf.json``
- Run ``asv run ALL``
- Add a new Numpy version
- Run with ``asv run ALL --skip-existing``

I would expect this to run all the benchmarks with only the new Numpy version that was added, but this does not run anything. It looks like if there was a benchmark run in *any* configuration then it won't run that benchmark at all, even in configurations that haven't been run yet.

I think the solution is that the skipping needs to be applied separately to each configuration/environment separately.

**Comment by philpep** [comment]
I'm currently trying to allow running only some specified combination of parameters in #593 , I think this could be used as a base for enhancing `--skip-existing` like you wish.

**Comment by astrofrog** [comment]
I have implemented a fix for this issue in https://github.com/airspeed-velocity/asv/pull/603
