### ISSUE TITLE
Change in benchmark names after refactor

### ISSUE THREAD

**Issue by astrofrog** [airspeed-velocity/asv#604]
For astropy we have some benchmarks that look like:

```python
class BaseClass:
    def read(self):
        # code here

class TimeA(BaseClass):
    time_read = BaseClass.read
```

Prior to https://github.com/airspeed-velocity/asv/commit/93a4e5a40f880984899a727e9adda4bb78c4a718, the benchmarks were called ``TimeA.time_read``, and afterwards they were called ``TimeA.read`` - I think this is an unintended change? (cc @philpep)

**Comment by pv** [comment]
Yes, looks unintended.

**Comment by philpep** [comment]
Thanks for reporting, I'm looking at this issue.
