### ISSUE TITLE
Benchmark sections don't show up in Safari

### ISSUE THREAD

**Issue by astrofrog** [airspeed-velocity/asv#607]
When looking at the benchmark results at http://www.astropy.org/astropy-benchmarks in Chrome and Firefox, I see section headings:

<img width="913" alt="screen shot 2018-01-15 at 13 48 47" src="https://user-images.githubusercontent.com/314716/34945357-f2637420-f9fa-11e7-8cc3-f7d7d71d014f.png">

However, these are not visible in Safari on MacOS X:

<img width="903" alt="screen shot 2018-01-15 at 13 48 40" src="https://user-images.githubusercontent.com/314716/34945359-f8edee56-f9fa-11e7-9596-3acf720507d8.png">

**Comment by pv** [comment]
Do you know why this is so? (Never used safari, so osx users are needed 
to debug and fix this. Doesn't repro in another webkit-based browser.)

**Comment by astrofrog** [comment]
Sorry for the noise, this was a cache issue (I updated asv recently and somehow it was using old js in Safari).
