### ISSUE TITLE
Consider making JSON output more compact

### ISSUE THREAD

**Issue by astrofrog** [airspeed-velocity/asv#609]
At the moment, the result JSON files include the names of each tests several times, e.g.

```json
    "benchmark_version": {
        "coordinates.FrameBenchmarks.time_init_array": "c674b97d5a26e5c61c240678ebdcc4a8fbb346db4aacedbb7868aefb3230f080",
        "coordinates.FrameBenchmarks.time_init_nodata": "c3d603a1d100c4d8f50750ddfac91c7db732186bbe5091b354ab1ee7bd4703d5",
        "coordinates.FrameBenchmarks.time_init_scalar": "defe667485d7109897f4a6a2770d80eb89ff9295c31bc941252bf4b8f6e15288",
...
    "ended_at": {
        "coordinates.FrameBenchmarks.time_init_array": 1517086912000,
        "coordinates.FrameBenchmarks.time_init_nodata": 1517086915000,
        "coordinates.FrameBenchmarks.time_init_scalar": 1517086918000,
...
    "started_at": {
        "coordinates.FrameBenchmarks.time_init_array": 1517086908000,
        "coordinates.FrameBenchmarks.time_init_nodata": 1517086912000,
        "coordinates.FrameBenchmarks.time_init_scalar": 1517086915000,
...
    "results": {
        "coordinates.FrameBenchmarks.time_init_array": {
```

For projects with many tests and commits, it would be more efficient to store this as a list of benchmarks with 'stared_at', 'results', and 'ended_at' keys for each one, to avoid repeating the long test names.

It would also be a bit more space efficient to store sections like:

```json
            "stats": [
                {
                    "ci_99": [
                        0.0023126445813953537,
                        0.002361580779069762
                    ],
                    "max": 0.0023916572325581296,
                    "mean": 0.0023257523279069763,
                    "min": 0.0023118635116279058,
                    "n": 10,
                    "q_25": 0.002314243011627908,
                    "q_75": 0.002323088261627908,
                    "std": 2.2691405732192584e-05,
                    "systematic": 0.0
                }
            ]
        },
```

without all the indentation as there is a lot of whitespace there. The precision of the values could probably also be reduced.

Finally, the hashes for the benchmark versions probably don't need to be as long as they are:

```json
        "coordinates.FrameBenchmarks.time_init_array": "c674b97d5a26e5c61c240678ebdcc4a8fbb346db4aacedbb7868aefb3230f080",
```

For Astropy, our results directory is now 600MB which is starting to make it painful to store in a repository, and many of these files aren't even using the new stats section above yet. It would be nice to consider having a more compact file format for the results for the long term.

**Comment by pv** [comment]
The result files could be also maintained in compressed json (gzip or bzip), which would probably achieve most of the same reduction.

**Comment by astrofrog** [comment]
@pv - I agree that plain text would be better - otherwise if a benchmark is added, the whole file has to be re-written.
