### ISSUE TITLE
Allow marking a class as non-benchmark

### ISSUE THREAD

**Issue by pitrou** [airspeed-velocity/asv#610]
It can be useful to define some benchmarks in an incomplete base class (e.g. without a `setup()` method), then inherit that base class in derived classes. Unfortunately `asv` by default treats all classes with `time_` methods as potential benchmark classes.

e.g.:
```
class BaseBenchmark:
    def time_do_something(self):
        do_something(self.data)

class IntBenchmark(BaseBenchmark):
    def setup(self):
        self.data = list(range(1000000))
```

A workaround is to have a `setup()` method raising `NotImplementedError` in the base class. But that feels like a hack, not a proper solution, to me :-)

**Comment by pv** [comment]
Yes, there clearly should be a way to do this, probably via an attribute.
Maybe `benchmark_type = None` or something similar

**Comment by pitrou** [comment]
Perhaps `abstract_class = True`? We can solve the inheritance problem by only looking up in the class `__dict__` instead of using `getattr`.

**Comment by isuruf** [comment]
I need this too. @pv, are you okay with @pitrou's suggestion? If so, I can look into implementing it.

**Comment by HaoZeke** [comment]
Now this can be done via `asv_runner` from version `0.2.1` on-wards.

```python
from asv_runner.benchmarks.mark import skip_benchmark

@skip_benchmark
class TimeSuiteTwo:
    def setup(self):
        self.d = {}
        for x in range(500):
            self.d[x] = None

    def time_keys(self):
        for key in self.d.keys():
            pass
```
