### ISSUE TITLE
0.2.2 (or 0.3) release?

### ISSUE THREAD

**Issue by yarikoptic** [airspeed-velocity/asv#617]
I have ran into #514 which was fixed after the last release (0.2.1, in June 2017), so wondered if/when next release planned and/or I am doomed to switch to the development version straight from git

Cheers

**Comment by pv** [comment]
No 0.2.x release is planned, but otoh it's not that much work to 
backport bugfixes.

**Comment by pv** [comment]
0.3 probably still waits for interleaved benchmark run support, as 
collecting benchmark statistics in a single run is not that useful 
otherwise.

**Comment by SylvainCorlay** [comment]
@rabernat @yarikoptic were you able to use the `conda_channels` JSON configuration key with the latest from master?

**Comment by yarikoptic** [comment]
@SylvainCorlay I'm not aware of this issue.  I was hoping for the release so all other fixes get released
