### ISSUE TITLE
asv find not bisecting a "failed" benchmark

### ISSUE THREAD

**Issue by asmeurer** [airspeed-velocity/asv#623]
I have a benchmark that returns "failed" in master, but runs in a few ms in the previous tag. I believe the "failed" is because of a timeout. I ran the benchmark manually and it ran in about 7 minutes. 

When I tried to use asv find to find this, it seems to be running each (merge) commit from master backwards, assumedly until it finds a non-failed. I was hoping it could actually do a bisection.

**Comment by pv** [comment]
`asv find` does use bisection search (on the linearized history).

Maybe what you are seeing is a linear search in the "benchmark discovery" phase, when asv needs to find at least one commit that builds?

**Comment by pv** [comment]
... but indeed, it does linear search when benchmarks fail:
https://github.com/airspeed-velocity/asv/blob/master/asv/commands/find.py#L171

**Comment by asmeurer** [comment]
Even then, a timeout should be considered slow for the purposes of bisection, not an error.

**Comment by pv** [comment]
Timeouts (which is a user-configurable property of the benchmark) is a benchmarking error, insofar as asv is concerned.
