### ISSUE TITLE
`git rev-parse master` can fail

### ISSUE THREAD

**Issue by pitrou** [airspeed-velocity/asv#631]
I'm trying to run benchmarks on Travis-CI. Unfortunately, "asv run" uses "git rev-parse master" to discover benchmarks, which fails as "master" doesn't necessary exist:
https://travis-ci.org/pitrou/arrow/builds/364763507#L866

The command being run is:
```
asv run --no-pull --show-stderr --quick ${TRAVIS_COMMIT}^!
```

**Comment by pv** [comment]
The 'master' I think comes from asv.conf.json --- I guess if that lists a non-existing branch, what can be done?

**Comment by pitrou** [comment]
The branch exists in normal setups, but when Travis-CI runs a branch build, "master" doesn't exist in the local repo. I'm currently working this around by running:
```
git fetch --depth=1 origin master:master
```

**Comment by pv** [comment]
For this specific code path, it could in principle just ignore the failure to look up the branch, which is in any case only used as a fallback if the commits specified explicitly fail to build.
