### ISSUE TITLE
A 'Master' Setup function

### ISSUE THREAD

**Issue by kaipak** [airspeed-velocity/asv#633]
Say I have a benchmark like below:

```
class mybench:
    setup(self):
        do some computationally expensive, resource intensive stuff
    
    def test1(self):
         do some useful calculation

    def test2(self):
         do some other useful calculation

    def teardown(self):
```

Based on observation, it seems that the current behavior is the following

1. setup
2. test1
3. teardown
4. setup
5. test2
6. teardown

Am I mistaken in this view? If not, is there a relatively straight forward way to do test1 and test2 with a single setup? In some cases, it would be nice to be able to rely on the results of test1 in test2, and in another case, setup may be really expensive... like downloading a few gigabytes of data or provisioning a VM perhaps.

**Comment by pv** [comment]
See `setup_cache`. 
`test1` and `test2` run in different processes, so saved state needs to go via disk.
