### ISSUE TITLE
skip time benchmarks within the benchmark function

### ISSUE THREAD

**Issue by philpep** [airspeed-velocity/asv#638]
We can skip benchmarks by raising ``NotImplementedError`` in ``setup()``.
For **track** benchmarks we can also skip in the function by returning ``float('nan')``.
But for **time** benchmark I cannot see how we can skip them from the function ?

Since **time** function return is unused, maybe we could use it to detect ``NaN`` and mark the result as skipped as for **track** benchmarks ? What do you think ?

**Comment by philpep** [comment]
Ok. I see that benchmarks are skipped if the `setup()` method raise `NotImplementedError`.

What do you think about extending this behavior to benchmark function (time or track) ?

I'm not a big fan of this behavior because this can unexpectedly hide a user code NotImplementedError, but since we do this in `setup()`, it seems reasonable.

**Comment by pv** [comment]
I think I won't change the current behavior, skipping from inside benchmark function was intentionally left out.
