### ISSUE TITLE
asv run problem

### ISSUE THREAD

**Issue by Adir7SK** [airspeed-velocity/asv#639]
After typing asv run, i get the message:

usage: asv.exe [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: asv.exe --help [cmd1 cmd2 ...]
   or: asv.exe --help-commands
   or: asv.exe cmd --help

error: invalid command 'run'

**Comment by pv** [comment]
How did you install it? For reference, it works for me on Windows 10 + Python from https://python.org.

E.g. as in the following 
```
"c:\program files\python36\python.exe" -mvenv env
env\scripts\activate.bat

pip install asv
asv run --help
```

**Comment by Adir7SK** [comment]
​I installed it exactly as you said, but it doesn't work. I'll try to
reinstall it later, and return to you if the same problem comes up.
​
