### ISSUE TITLE
Precise measurement

### ISSUE THREAD

**Issue by Adir7SK** [airspeed-velocity/asv#641]
Hi, using ```asv run```, ```asv publish``` and then ```asv preview``` gives different results for the same unchanged functions (difference of milliseconds). Is there a way to measure the same many times, and then take the average of the measurements?
Thanks

**Comment by pv** [comment]
And be aware that CPU frequency scaling etc. factors affect results,
and cause variations on the time scales of many seconds. This can lead
to needing unmanageably long measurement time, so you'll need to
disable these features in your OS if you need precise measurements
faster.

**Comment by pv** [comment]
It's there:
https://asv.readthedocs.io/en/stable/writing_benchmarks.html#timing
