### ISSUE TITLE
pip dependencies with url

### ISSUE THREAD

**Issue by isuruf** [airspeed-velocity/asv#644]
If a dependency is declared like `pip+git+https://github.com/org/repo@1.0` it correctly installs it, but `asv publish` fails to find the machine.json probably because the results are now in a directory structure as the `/` in the url are interpreted as path separators.

How do you want to handle this? Escape the pip dependency before writing to a file? Figure out a way to find machine.json? Use a requirements file?

I can do the work if you can tell me what you want to do

**Comment by pv** [comment]
Fixed by gh-498?

**Comment by pv** [comment]
However, if so, the fix is included in asv 0.2.1

**Comment by isuruf** [comment]
You are right.
