### ISSUE TITLE
min repeat for long benchmarks with number = 1

### ISSUE THREAD

**Issue by philpep** [airspeed-velocity/asv#653]
Hello,

We have some time benchmarks that need `setup()` and `teardown()` called between each call of the time benchmark. So we set `number = 1`. The benchmark is parameterized and depending on the variant used and the hardware used, a single benchmark run can take between 1 minutes to 45 minutes.
To control how many repeat will be done we have to set `repeat` and `sample_time` on a per-variant basis in `setup()`, this works but it's still hardware dependent and can lead to having a result based on a single run (see `too_slow()` in `asv.benchmark.TimeBenchmark.benchmark_timing()`).

So we think about introducing a new `min_repeat` attribute, if set this will ensure the benchmark run at least `min_repeat` without regard to `sample_time`. What do you think ?

**Comment by pv** [comment]
I wonder if it would be better to adjust how `max_time` behaves, instead of introducing new attributes? 

Namely, when both `number` and `repeat` are set by the user, I wonder if the whole `max_time` check should be skipped. Would this solve the issue for you?

**Comment by pv** [comment]
In particular, if `repeat` is set by user, then I think it should always do the exact number of repeats...

**Comment by marmoute** [comment]
In our usecase, we have variants with very different runtime. We are benchmarking Mercurial, a command line source control tool. The runtime on a command of a small repo can involve very few work while the same command of a much larger repository can involve very long processing. We also test commands in various situation. A pull between two repositories already in sync will be very fast, while a pull bringing thousand of new revisions will be slower.

For the fast operation, the current ASV heuristic works well. default sample_time and repeat gives good results. However for the longer one the max_time computation cutoff the execution too soon.

I see two easy way to improve our usecase:

* add a `min_repeat` attributes that feeds into `min_timeit_count` to force a minimal number of run
* add a `max_time` attributes to control the maximum run time before we cut the execution loop short.

Having these two options will allow us to get reasonable result for long running variants while keeping the default behavior for the others.
