### ISSUE TITLE
Conda channels not taken into account in `asv.conf.json`

### ISSUE THREAD

**Issue by SylvainCorlay** [airspeed-velocity/asv#657]
(Installed ASV from source, with the tip of the master branch).

It does not seem that the `conda_channels` key is taken into account in the `asv.conf.json`.

**Comment by pv** [comment]
Try wiping the environments so that asv recreates them. Does the issue
persist?

**Comment by SylvainCorlay** [comment]
Yes. Not finding package xtl, which is a `conda-forge` (https://anaconda.org/conda-forge/xtl)

``` sh
            STDOUT -------->
             Solving environment: ...working... failed
             STDERR -------->
             
             ResolvePackageNotFound: 
               - xtl=4.9
```

Not sure if there is some temporary thing for the environment going on.

**Comment by SylvainCorlay** [comment]
```JSON
{
    "version": 1,
    "project": "xtensor",
    "project_url": "http://quantstack.net/xtensor",
    "repo": ".",
    "branches": ["master"],
    "dvcs": "git",
    "environment_type": "conda",
    "conda_channels": ["conda-forge", "defaults"],
    "install_timeout": 600,
    "show_commit_url": "http://github.com/QuantStack/xtensor/commit/",
    "matrix": {
        "xtl": ["4.10"],
        "xsimd": ["5.0"]
    },
    "benchmark_dir": "benchmarks",
    "env_dir": ".asv/env",
    "results_dir": ".asv/results",
    "html_dir": ".asv/html"
}
```

**Comment by SylvainCorlay** [comment]
Thanks very much for your help!

**Comment by pv** [comment]
The problem is that there's no version "4.10" of xtl on conda-forge.
You probably meant to write "0.4.10".

**Comment by SylvainCorlay** [comment]
Yep, that is it. So sorry!

![giphy](https://user-images.githubusercontent.com/2397974/42227674-4c72b5cc-7ee2-11e8-8d58-9ec616af6a78.gif)
