### ISSUE TITLE
Website broken when mixing results from asv 0.2 and 0.3dev

### ISSUE THREAD

**Issue by Juanlu001** [airspeed-velocity/asv#658]
I generated benchmarks with asv 0.2 in one machine, and then when switching to another machine I had to upgrade to 0.3dev because of #645. Now I have results coming from both versions in the repository:

https://github.com/poliastro/poliastro-benchmarks/tree/results/results/

And I suspect this broke the website:

http://poliastro.github.io/poliastro-benchmarks

(by the way, I generate the results with asv 0.3dev, https://travis-ci.org/poliastro/poliastro-benchmarks/builds/400674859 and https://github.com/poliastro/poliastro-benchmarks/blob/results/.travis.yml#L14)

In Chromium, I don't see the more recent benchmarks, and when I try to visualize only those, I get this JavaScript error:

![screenshot from 2018-07-06 09-19-21](https://user-images.githubusercontent.com/316517/42365397-a969a916-80fe-11e8-9994-53f96be9bcc8.png)

In Firefox I don't see them either, and I get this other error:

![screenshot from 2018-07-06 09-30-27](https://user-images.githubusercontent.com/316517/42365603-3ff516f4-80ff-11e8-9106-1e2e23b5469c.png)

**Comment by Juanlu001** [comment]
By the way, I rerun those tests with asv 0.2, overwrote the results, and the issue is gone.

**Comment by pv** [comment]
Can you give a permalink to the problematic result set.
It works ok for me for poliastro-benchmarks@2450df388b6cda4b5d543e9885f207b1fb181108

**Comment by Juanlu001** [comment]
* Works: https://github.com/poliastro/poliastro-benchmarks/commit/2450df388b6cda4b5d543e9885f207b1fb181108
* Broke: https://github.com/poliastro/poliastro-benchmarks/commit/51581608b770e3b304daf973871da262c95f1a48
* Fixed: https://github.com/poliastro/poliastro-benchmarks/commit/099f7929e96affd33634b9f2e49689ff3c3aa7c9

**Comment by pv** [comment]
Looks this is about benchmark versioning:
https://asv.readthedocs.io/en/latest/writing_benchmarks.html#benchmark-attributes

There are a few steps that need to be done to upgrade results: you probably need to delete `benchmarks.json`, and regenerate it with asv 0.3.dev, before `asv publish`.

**Comment by pv** [comment]
You can check if https://github.com/airspeed-velocity/asv/pull/660 makes the UX here nicer.
