### ISSUE TITLE
setup() granularity and subtracting related tasks

### ISSUE THREAD

**Issue by tylerjereddy** [airspeed-velocity/asv#664]
One tricky thing to deal with is state-dependent benchmarks--sorting a list or handling a `StringIO` object as I mentioned for [NumPy](https://github.com/numpy/numpy/pull/11422#issuecomment-403247951) and [pandas](https://github.com/pandas-dev/pandas/pull/21807) benchmarks.

The problem is that `setup()` runs between **repeats**, but not between **iterations** within repeats, so if you point to an object like a list you want to sort or a StringIO object you want to read in, the work on that object will already be done in subsequent iterations and the timings will do less or close to nothing depending on the task being timed in `time_operation`.

I don't think there's any obvious way around this (since that's how `timeit` works -- single setup then a bunch of iterations with no setups in between). However, one possibility might be exposing convenient functionality to subtract away the timing of any operations you aren't interested in as implied by [Raymond Hettinger in a comment about sort benchmarking](https://stackoverflow.com/questions/8220801/how-to-use-timeit-module#comment11535453_8220943).

cc @stefanv , @mattip

**Comment by pv** [comment]
Set `number = 1`.

**Comment by tylerjereddy** [comment]
If I set `repeat = 1` and `number = 1` as shown below the `time_benchmark` function seems to effectively ignore my hardcoded specifications for repeats and iterations per repeat (using a relatively recent version of the asv dev branch):

```python
 67 class LoadtxtCSVComments(Benchmark):                                                                                       
 70                                                                                 
 71     params = [10, int(1e2), int(1e4), int(1e5)]                                 
 72     param_names = ['num_lines']                                                 
 73                                                                                 
 74     def setup(self, num_lines):                                                 
 75         self.repeat = 1                                                         
 76         self.number = 1                                                         
 77         data = [u'1,2,3 # comment'] * num_lines                                                   
 82         self.data_comments = StringIO(u'\n'.join(data))                         
 83         print("running setup for num_lines:", num_lines)                        
 84                                                                                 
 85     def time_comment_loadtxt_csv(self, num_lines):                                                              
 95         print("running bench test proper for num_lines:", num_lines)            
 96         self.data_comments.seek(0)                                              
 97         np.loadtxt(self.data_comments,                                          
 98                    delimiter=',') 
```

output in log file with print functions being called way more than expected for the iterations: 
[log.txt](https://github.com/airspeed-velocity/asv/files/2186279/log.txt)

**Comment by tylerjereddy** [comment]
If I just print from the setup() to clean up the output:

```
                For parameters: 10
                running setup for num_lines: 10
                running setup for num_lines: 10
                
                For parameters: 100
                running setup for num_lines: 100
                running setup for num_lines: 100
                
                For parameters: 10000
                running setup for num_lines: 10000
                running setup for num_lines: 10000
                
                For parameters: 100000
                running setup for num_lines: 100000
```

Looks like setup() only gets called once for the largest set, but the entire suite runs in way less than 60 seconds. I suppose there may be warm up runs in some cases or something?!

**Comment by pv** [comment]
Yes, there is warmup if you are using asv 0.3.dev, see the
documentation.

**Comment by pv** [comment]
Also, there's no need to set `repeat = 1` unless you really want to
sample only a single data point. You can leave it at the default value
(0) otherwise.

**Comment by pv** [comment]
In addition, you can set
```
time_comment_loadtxt_csv.number = 1
```
or
```
number = 1
```
in the class definition, instead of setting the values dynamically in
setup().

**Comment by tylerjereddy** [comment]
This was mostly for debug purposes; I see that setting `warmup_time = 0` seems to remove the calls I wasn't expecting in a debug context. Looks like repeat and number don't affect warmup behavior, which I suppose is sensible. Closing, thanks
