### ISSUE TITLE
One or more external (JavaScript) dependencies of airspeed velocity failed to load

### ISSUE THREAD

**Issue by astrofrog** [airspeed-velocity/asv#669]
At some point in the last few days, the astropy benchmarks stopped being rendered correctly:

<img width="912" alt="screen shot 2018-07-10 at 14 25 04" src="https://user-images.githubusercontent.com/314716/42512660-1dc22c60-844d-11e8-8cd3-99a184c83f29.png">

The benchmarks page is http://www.astropy.org/astropy-benchmarks - is this something that is affecting other projects too?

**Comment by pv** [comment]
The error message probably is correct on what happened -- do you have
network connectivity issues to the CDNs? (It works for me.)

**Comment by pv** [comment]
In any case, I'm planning to start bundling the depedency JS libraries
rather than loading them from CDN, so CDN issues like this would be
generally fixed by gh-663

**Comment by astrofrog** [comment]
@pv - it seems to be working again - I'm not sure which library was the issue, but feel free to close this.
