### ISSUE TITLE
Big time difference for benchmarks that require high warmup

### ISSUE THREAD

**Issue by Juanlu001** [airspeed-velocity/asv#677]
I was running a benchmark with latest asv 0.3dev0 and I observed a big time difference from asv 0.2.

* 0.2 https://github.com/poliastro/poliastro-benchmarks/blob/df6a71330f08c0c0ae1369818bc5af8106bba62f/results/ks1/d32f3ab8-conda-py3.6-matplotlib2.1-nomkl-numba-numpy1.14-scipy1.0.json#L31
* 0.3dev0 https://github.com/poliastro/poliastro-benchmarks/blob/f47fb57f2db0d76649ae7337867221b3738f057a/results/ks1/d3238535-conda-py3.6-matplotlib2.1-nomkl-numba-numpy1.14-scipy1.0.json#L34

After doing a git bisect, I arrived to [this commit](https://github.com/airspeed-velocity/asv/commit/db5cc300d39eb890292cf979d90f255b57dc9887) and [pull request](https://github.com/airspeed-velocity/asv/pull/493), which as far as I understand has not been backported to 0.2 yet.

This particular benchmark calls a function accelerated with `@jit(nopython=True)`, so I suspected that warmup time had something to do with it. After playing a little bit with the parameters, I found that this diff brought back the old time measurement with asv 0.3dev0:

```diff
diff --git a/benchmarks/examples.py b/benchmarks/examples.py
index 13e86d8..d034eed 100644
--- a/benchmarks/examples.py
+++ b/benchmarks/examples.py
@@ -3,3 +3,5 @@ from poliastro.examples import iss
 
 def time_propagate_iss_one_period():
     iss.propagate(iss.period)
+
+time_propagate_iss_one_period.repeat = 3
```

So there is ~~a UX issue and~~ a measurement issue:

* ~~The UX issue is that, as far as I know, there's no way to know _a posteriori_ how many repetitions, number of samples, etc did asv compute for a benchmark, as this information is not stored in the results.~~
* The measurement issue is that, with the current benchmark methodology, if a function requires a "big" warmup time (in this case, doing the numba JIT compilation), it will be run only once, which might or might not be representative of the intended result.

**Comment by pv** [comment]
Right -- 0.3 is not released in part because the benchmark methodology is not really finalized.

**Comment by Juanlu001** [comment]
Sorry, the UX issue does not exist - these parameters are stored in `benchmarks.json`.

**Comment by pv** [comment]
When they're automatically determined, you'll need to pass `--record-samples` to have the necessary information stored.
