### ISSUE TITLE
Slightly OT: extend asv to benchmark other things?

### ISSUE THREAD

**Issue by fmaussion** [airspeed-velocity/asv#678]
Hi asv! Thanks for this great tool, we set it up for our [glacier model](https://cluster.klima.uni-bremen.de/~github/asv/#/) project a couple of weeks ago.

Now that we have this, there are other things we would like to start benchmarking ;-). Mostly, we would like to track the *quantitative* results of our model for selected use-cases. Note that this is not to replace unit tests (which check that the model does reasonable things) but complement them by checking that the model results are reproducible through time (updates + dependency updates). 

As an example: our model computes the estimated volume of a glacier. We don't know the real volume of this glacier, so there is no unit test for this (we just check that it is valid within a range of reasonable values). Another example would be to check the predicted volume of many glaciers, a test which is too expensive to be run on Travis but OK to run on our HPC environment (which currently runs asv). 

I know this is not the intended use for asv, but asv already has a lot of the functionality required for such a new benchmarking tool:
- detection of benchmarking functions
- plotting the result of computations as a function of time
- detecting commits which break things
- etc.

Are there any plans on extending asv with new kinds of benchmarks?

**Comment by pv** [comment]
You can track any numerical values with the track_ benchmarks, and combine that with setup_cache.

**Comment by fmaussion** [comment]
Ha! Sorry I missed that. For reference: https://asv.readthedocs.io/en/stable/writing_benchmarks.html#tracking-generic

Thanks @pv , that's very useful.
