### ISSUE TITLE
Bug of asv profile with snakeviz (TypeError: '>' not supported between instances of 'float' and 'NoneType')

### ISSUE THREAD

**Issue by astafan8** [airspeed-velocity/asv#679]
I was following the [documentation of using asv](https://asv.readthedocs.io/en/stable/using.html) for my project. Everything worked fine, but then I've decided to profile using `asv`, and use a GUI tool for viewing the results.

I could not install `RunSnakeRun` due to syntax error in Python 3 (I'm using Python 3.6). Hence, I've decided to install `snakeviz` because it is also mentioned in the `asv` docs. The installation went well, and I've started the `asv profile` command. 

During the execution of the command, `asv` printed an exception stack trace into the command line (see below). The snakeviz launched successfully, and displayed the results (hopefully) properly. Still, i've decided to report the issue (seems like a tiny bug).

```bash
asv profile --gui snakeviz benchmarks.TimeSuite.time_keys
```
The output in the command line is the following:
```
· Discovering benchmarks
·· Uninstalling from conda-py3.6
·· Building for conda-py3.6
·· Installing into conda-py3.6
· Profile data does not already exist. Running profiler now.
·· Uninstalling from conda-py3.6
·· Building for conda-py3.6
·· Installing into conda-py3.6
·· Benchmarking conda-py3.6
··· Running benchmarks.TimeSuite.time_keys                                                                                          7.66μsException i
n thread Thread-58:
Traceback (most recent call last):
  File "c:\users\a-miasta\appdata\local\continuum\anaconda3\envs\qcodes\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\users\a-miasta\appdata\local\continuum\anaconda3\envs\qcodes\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\a-miasta\appdata\local\continuum\anaconda3\envs\qcodes\lib\site-packages\asv\util.py", line 407, in watcher_run
    if time.time() - start_time[0] > timeout:
TypeError: '>' not supported between instances of 'float' and 'NoneType'
```

**Comment by pv** [comment]
Right, it's a bug -- I guess nobody else has tried the snakeviz plugin in a long time.

As a workaround, replace timeout=None with timeout=365*24*60*60 at the end of ..../site-packages/asv/plugins/snakeviz.py
