### ISSUE TITLE
graphs folder is not generated

### ISSUE THREAD

**Issue by isuruf** [airspeed-velocity/asv#722]
I upgraded to master, deleted the .asv folder and redid benchmarks for two commits.
After publishing, the graphs are empty and there's no .asv/html/graphs folder anymore. Any idea why that is?

**Comment by pv** [comment]
No, worksforme. Upgraded from what version?

**Comment by pv** [comment]
Are there any result files?
Are the commits benchmarked on a branch configured in asv.conf.json?

**Comment by isuruf** [comment]
> Are the commits benchmarked on a branch configured in asv.conf.json?

Thanks. I wasn't
