### ISSUE TITLE
asv compare should use the unit attribute for displaying

### ISSUE THREAD

**Issue by isuruf** [airspeed-velocity/asv#724]
I have a benchmark that counts number of objects with a `track_` method, but `asv run` outputs minutes, hours, days.

**Comment by pv** [comment]
Cannot reproduce.
Have you set an `unit = "seconds"` attribute e.g. on the class=?

**Comment by pv** [comment]
Reopen if there's a reproducible example case.

**Comment by isuruf** [comment]
It's asv compare that is displaying wrong units. Not asv run

**Comment by isuruf** [comment]
It's https://github.com/airspeed-velocity/asv/blob/049f4fa74d981a4a1996b2c109b912ea79fd462f/asv/commands/compare.py#L335 that's assuming seconds

**Comment by isuruf** [comment]
Thanks
