### ISSUE TITLE
Benchmarking parallel processing

### ISSUE THREAD

**Issue by jni** [airspeed-velocity/asv#725]
Hi,

Over at scikit-image we are trying to benchmark the performance of using OpenMP on some functions. We've found that because ASV reports CPU time instead of wall time, it gives counterintuitive results, where more CPUs result in worse timings. Does ASV have a recommended way to measure multicore scaling issues?

See discussion [here](https://github.com/scikit-image/scikit-image/pull/3120#issuecomment-417836363) where asv benchmarks take longer with increasing `n_cpus`, while `timeit` shows that they get faster with decent scaling.

**Comment by pv** [comment]
You can use the `timer` attribute to change to wall time, if that's wanted.

**Comment by jni** [comment]
@pv can you point me to some part of the documentation or an example that shows me what you are talking about?

**Comment by pv** [comment]
https://github.com/airspeed-velocity/asv/blob/master/docs/source/writing_benchmarks.rst#timing
