### ISSUE TITLE
Problem with v0.3 (II): ModuleNotFoundError

### ISSUE THREAD

**Issue by prisae** [airspeed-velocity/asv#740]
I encountered 2 problems with `v0.3.0`. I report them separately.

The second error is:

```
   ModuleNotFoundError: No module named 'numpy'
```

- If I run the test with `asv v0.2.2` it runs just fine.
- If I run the test with `asv v0.3.0` AFTER having run at least one test with `asv v0.2.2` it will run fine as well.
- But on a new install with `asv v0.3.0` it fails.

There must have been a change how required modules are installed.

**Comment by pv** [comment]
This occurs only when running tests?
What is the full error traceback?
What command do you use to run the tests?

**Comment by pv** [comment]
Or maybe you mean "empymod benchmarks" and not "asv test suite"?

FWIW, empymod benchmarks run fine for me out of the box.

**Comment by prisae** [comment]
I think #739 and #740 are related, but the error message differs at time. I close this one, and continue reporting on #739.
