### ISSUE TITLE
asv run --interleave-processes doesn't respect build_command config

### ISSUE THREAD

**Issue by mtreinish** [airspeed-velocity/asv#741]
I have a project where I need to run cmake to generate a setup.py so I have a custom build_command set in the asv.conf.json to run cmake and the setup.py build. This works well and allows me to run benchmarks using asv run with no issues. However, when I was trying the --interleave-processes it skips all the benchmarks and outputs:

`(null): can't open file 'setup.py': [Errno 2] No such file or directory`

Which likely means that asv run isn't using the build_command from the config file when --interleave-processes is set.

This is occurring using asv==0.3 and python 3.7

**Comment by pv** [comment]
There should be no special handling in --interleave-processes.
What is the custom build_command and what do your install/uninstall commands do?

**Comment by mtreinish** [comment]
I'm not really doing anything special, just calling cmake before calling setup.py. The relevant sections of the asv.conf.json are:

```
    "install_command": ["python -mpip install {build_dir}"],
    "uninstall_command": ["return-code=any python -mpip uninstall -y {project}"],
    "build_command": [
        "return-code=any /usr/bin/cmake .",
        "python setup.py build"
    ],
```
But, pulling that out of the config and looking at it again I just figured out what was going on. With interleave-processes set cmake is failing and setup.py is never being generated because it was running a version of the repo before there was a setup.py or a cmake (it started at the oldest commit instead of the newest)

**Comment by pv** [comment]
Ok, thanks for clarification.
