### ISSUE TITLE
Access paths from benchmark script

### ISSUE THREAD

**Issue by egpbos** [airspeed-velocity/asv#773]
I would like to have access to the paths set in the [environment variables](https://asv.readthedocs.io/en/stable/env_vars.html), so that I can use those in my benchmarks (e.g. to load input data or to run an external command through `subprocess`). When I print `os.environ` from a benchmark script, the `ASV_*` variables are not currently there. Is this supposed to be like this or is there some problem in my setup? I'm running `asv` on macOS from zsh.

**Comment by egpbos** [comment]
The variables aren't there when run from bash either, so zsh doesn't seem to be the problem.

**Comment by egpbos** [comment]
My workaround for the moment is to use PWD (`os.getenv("PWD")`), but I'd rather just use something like `asv.env_path` or `asv.conf_path`.

**Comment by egpbos** [comment]
If I understand correctly, I should be able to access the `ASV*` environment variables from my benchmark scripts. However, when I print `os.environ` from a benchmark script, I don't see them. Any ideas why this could be?

**Comment by pv** [comment]
Several of the env vars are tested in current tests.
If you want to add more, they probably would go in `test/test_environment.py`
