### ISSUE TITLE
Support staged benchmarks

### ISSUE THREAD

**Issue by mrocklin** [airspeed-velocity/asv#778]
I have a computation that looks like the following:

```python
x = a()
y = b(x)
z = c(y)
```

And I would like to build longitudinal benchmarks for each of `a`, `b`, and `c`.  Unfortuantely there is a fair amount of runtime state, so setting this up as three independent benchmarks is somewhat difficult, I'd really like to be able to pass data through from stage to stage without cleaning things up.

Is there any way to do this with ASV today?  If not, then would a change supporting this be in-scope if I wanted to work on this?

(My apologies if this has been discussed already.  I didn't see anything after a brief review through the current issues)

cc @mike-wendt

**Comment by pv** [comment]
See #446

**Comment by mrocklin** [comment]
Thanks @pv .  My apologies for the noise.
