### ISSUE TITLE
ENH: Continuous status message for improvement and regression should be different.

### ISSUE THREAD

**Issue by rok** [airspeed-velocity/asv#797]
When I use `asv continuous` in CI setting I want to fail commits that regress performance. As the message is the [same for regression or improvement](https://github.com/airspeed-velocity/asv/blob/137a1e8945e983e25d16b579f2cd62f18fe48962/asv/commands/continuous.py#L146) it's hard to have CI distinguish the cases by text output.

I propose to change the messages from:
* Improvement: `SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.`
* No change: `BENCHMARKS NOT SIGNIFICANTLY CHANGED.`
* Regression: `SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY.`

To:
* Improvement: `SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY. IMPROVEMENT.`
* No change: `BENCHMARKS NOT SIGNIFICANTLY CHANGED.`
* Regression: `SOME BENCHMARKS HAVE CHANGED SIGNIFICANTLY. REGRESSION.`

**Comment by mitar** [comment]
This has now been fixed with #799.
