### ISSUE TITLE
force-reinstall breaks when packages not on PyPI are used

### ISSUE THREAD

**Issue by isuruf** [airspeed-velocity/asv#822]
https://github.com/airspeed-velocity/asv/pull/806 introduced force-reinstall. With force-reinstall dependencies are reinstalled, but some dependencies on github only (no pypi) are not found.

**Comment by isuruf** [comment]
We could add `--no-deps`, but if a project is depending on dependencies being installed at this stage, it'll get broken.

**Comment by pv** [comment]
Ah, annoying it reinstalls everything.
The remaining fix is probably to chdir to eg. environment directory for the wheel installation. For backward compat needs to be done by changing the default command, which probably requires addition to the install_command syntax as its not real shell thanks to crossplatform.

**Comment by tylerjereddy** [comment]
Ah, maybe this is why I'm now seeing `ERROR: Cannot uninstall 'numpy'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.` while trying to reproduce work on the SciPy paper asv figure. It does indeed follow a ` --force-reinstall` pip command.
