### ISSUE TITLE
undefined variables `run`, `params` in benchmark.py

### ISSUE THREAD

**Issue by jbrockmendel** [airspeed-velocity/asv#856]
in Benchmark.do_profile.  Is there some globals-related magic at work here?

**Comment by pv** [comment]
https://github.com/airspeed-velocity/asv/blob/master/asv/benchmark.py#L589

**Comment by jbrockmendel** [comment]
So it is globals trickery?  Would a comment to that effect be worthwhile?

**Comment by pv** [comment]
The code it appears in is self-explanatory and short. If you want to flag it with some special comment that silences the statics analyzers you are using, PRs welcome.
