### ISSUE TITLE
change default behavior of asv run to use --python=same?

### ISSUE THREAD

**Issue by rgommers** [airspeed-velocity/asv#872]
Perhaps this ship has sailed, but it has annoyed me for a long time and it turns out I'm not alone so here goes.

This is my typical experience:
```
$ asv run  # starts downloading and building stuff
$ <Ctrl-C>
$ asv run --python=same
```

The default behavior makes sense for CI or running a benchmark server for a project. For use during development though, `--python=same` is much more useful. Since the former can be set up once in a CI script or cron job and forgotten about, while the latter you'll run into each time unless you write a wrapper around the `asv` cli interface (like SciPy does with `runtests.py`), the default behavior is suboptimal imho.

And yes, I know about `asv dev`, that's not the answer since `--quick` results are usually all over the place.

The solution could also be to drop `--quick` from `asv dev`, or to introduce a new command. Either way, not having any command with the expected default behavior is not great, so any of these would be a nice usability improvement.

**Comment by pv** [comment]
I'd rather change `asv dev` to be equivalent to `asv run --python=same` (gh-874).

**Comment by rgommers** [comment]
Awesome, thanks @pv
