### ISSUE TITLE
Fatal Error: ASV on Windows Launching `sh.exe` and Terminating

### ISSUE THREAD

**Issue by yehoshuadimarsky** [airspeed-velocity/asv#887]
On Windows, I setup a benchmark project and suite, then I ran `asv check` (from `cmd.exe`), but I am getting the output below. 

    C:\Users\[USER]\Documents\GitHub\[REPO]>asv check
    · Discovering benchmarks      2 [main] sh 5420 C:\Program Files\Git\usr\bin\sh.exe: *** fatal error in forked process - MapViewOfFileEx '(null)'(0x1F8), Win32 error 5.  Terminating.
      1 [main] sh 12488 fork: child 5420 - died waiting for dll loading, errno 11
      4 [main] sh 11552 C:\Program Files\Git\usr\bin\sh.exe: *** fatal error in forked process - MapViewOfFileEx '(null)'(0x1F8), Win32 error 5.  Terminating.

And this keeps repeating until I kill it. Can't figure out the problem. Issue seems to be with ASV calling the `sh.exe` in the Git folder, but I never use that so not sure why it's doing that.

System Information:
- Windows 10 Pro v1903 build 18362.418
- Git 2.18.0
- ASV 0.4.1
- Conda 4.7.12
- Python 3.7.3

Any help would be greatly appreciated! Thanks.

**Comment by pv** [comment]
This is an issue with your git installation (asv is calling git, git is calling sh and failing for some reason).
