### ISSUE TITLE
Summary plot can be misleading

### ISSUE THREAD

**Issue by pllim** [airspeed-velocity/asv#894]
Summary plot may show that performance has degraded:

![ex_summary_plot](https://user-images.githubusercontent.com/2090236/68407039-da516400-0150-11ea-9a17-32fa534ce369.jpg)

But this is not the case when you click on the plot to see the actual benchmark data:

![ex_expanded_plot](https://user-images.githubusercontent.com/2090236/68407075-e806e980-0150-11ea-9755-8d73e27778bb.jpg)

xref https://www.astropy.org/astropy-benchmarks/#modeling.compound.EvaluateCompoundModelWithUnits.time_medium

@astrofrog ~should know which~ said dev `asv` version was used.

**Comment by astrofrog** [comment]
We use asv dev: https://github.com/astropy/astropy-benchmarks/blob/results/.travis.yml#L14

**Comment by pv** [comment]
Probably some issue with the missing data filling.
Relevant code here if someone wants to take a look: https://github.com/airspeed-velocity/asv/blob/df83afa803117271785d7f7952e5927d515ea225/asv/graph.py#L323-L373
