### ISSUE TITLE
REF: install asv in the profiled environment

### ISSUE THREAD

**Issue by jbrockmendel** [airspeed-velocity/asv#908]
Having asv install itself in the profiled environment would open up a lot of options.  In particular, I think it would be necessary for something like #482 to be implemented.

I'd like to poke at this and see what it makes possible, but my first couple attempts at injecting asv into the environment failed.  @pv is there an easy way to do this?

**Comment by HaoZeke** [comment]
Not required anymore. `asv_runner` is installed per environment, and includes decorators.
