### ISSUE TITLE
Drop PY2 support?

### ISSUE THREAD

**Issue by jbrockmendel** [airspeed-velocity/asv#909]
A fair amount of compat code could be removed if PY2 support were dropped.  If I understand correctly, it could even be dropped for everything but benchmark.py and retain most of the relevant functionality; is that correct?

**Comment by dorothykiz1** [comment]
What are your thoughts on dropping Py2 support and all its dependencies in asv so that we unlock the use of  Python 3 syntax modules in the asv codebase?

**Comment by datapythonista** [comment]
Personally I'd do it immediately after the release (#967). I guess we can request Python 3.7 or 3.8.

Then we can update `setup.py` (https://github.com/airspeed-velocity/asv/blob/master/setup.py#L264), set up the CI to test with the minimum and the latest Python version, and then code can be slowly improved after that.

Any comment or objection to the above?

**Comment by HaoZeke** [comment]
I don't think there's any other Python 2x code left, if so they can be removed by PRs without this issue..
