### ISSUE TITLE
Compatibility with the latest virtualenv

### ISSUE THREAD

**Issue by frenzymadness** [airspeed-velocity/asv#923]
Hello.

asv seems to be incompatible with the latest virtualenv (20.0.20) because it uses `--no-site-packages`. This option has been deprecated for some time ([since 2011](https://virtualenv.pypa.io/en/legacy/changes.html#v1-7-2011-11-30)) and it has been removed because disallowed access to system site-packages is the default now.

**Comment by pv** [comment]
Fixed in master, bugfix release soon.
