### ISSUE TITLE
Guidelines for writing Benchmarks for a General Repository.

### ISSUE THREAD

**Issue by GTron-1729** [airspeed-velocity/asv#927]
As per asv documentation it tell us how to write benchmarks, But I want to write benchmarks for say any repo. So, what kind of benchmarks should I write? How do I start? do I need to understand full repo to write any benchmark? Give me a beginner guideline with some sample benchmarks, without me fully understanding the repo? Help would be appreciated.

**Comment by HaoZeke** [comment]
Now in https://github.com/HaoZeke/asv_samples
