### ISSUE TITLE
How could I set `setup()` runs only once?

### ISSUE THREAD

**Issue by karajan1001** [airspeed-velocity/asv#930]
I have a benchmark class like

```
class bench_something():
    repeat = (1, 1, 60.0)
    number = 10
    warmup_time = 0

    def setup(self):
        self.a = 0
        print("start " * 10)
    
    def teardown(self):
        print("end " * 10)

    def time_status(self):
        print("a:", self.a)
        self.a += 1
```    

I want this benchmark `setup()` runs once and the `time_status()` runs ten times. But the result is 
![Screenshot from 2020-06-01 21-13-31](https://user-images.githubusercontent.com/6745454/83412618-031eab00-a44d-11ea-8044-d0b26c06037e.png)

The `setup()` runs twice, and the `time_status()`  runs only once for the second time.

What's wrong with my benchmark? How could I set to make `setup()` run only once?

**Comment by karajan1001** [comment]
My `asv` version `0.4.1`

**Comment by pv** [comment]
Can't reproduce it with that example. Can you get it to appear from
clean slate in a "asv quickstart" project?

**Comment by karajan1001** [comment]
I run it in a clean project. My benchmark:
```
def write(line):
    with open('[somepath]/result.txt', 'a') as f_w:
        f_w.write("{}\n".format(line))

class BenchSomething():
    repeat = (1, 1, 60.0)
    number = 10
    warmup_time = 0


    def setup(self):
        self.a = 0
        write("start " * 10)

    def teardown(self):
        write("end " * 10)

    def time_status(self):
        self.a += 1
        write("a:{}".format(self.a))
```

![Screenshot from 2020-06-01 22-29-51](https://user-images.githubusercontent.com/6745454/83419492-bab8ba80-a457-11ea-9efb-8e0fb55614e2.png)


My result
![Screenshot from 2020-06-01 22-29-24](https://user-images.githubusercontent.com/6745454/83419485-b7bdca00-a457-11ea-8f1a-e4f44bbe1b05.png)

**Comment by pared** [comment]
@karajan1001 
In the case of an in-memory setup, you could use `setup_cache` method.

**Comment by karajan1001** [comment]
@pv Thank you, it seems that the question is because I missed the `--profile` after `asv run`. The problem had been solved, It is OK to close this issue. Thanks again.

**Comment by pv** [comment]
Right, profiling will run the benchmark a separate time (since profiling would change timings).
