### ISSUE TITLE
ENH: Update requirements section of results with exact versions of packages

### ISSUE THREAD

**Issue by kevingerman** [airspeed-velocity/asv#931]
It would be helpful if the Conda Environment plugin were able to update the results#requirements with the exact conda version of a dependency rather than the conda refspec that was used in the asv.conf.json matrix.  Having the exact versions are helpful for reproduction as well as seeing when a new revision of a dependency slipped in.

**Comment by HaoZeke** [comment]
While this would be nice, it is a little out of scope for `asv`, especially since `asv` is meant to run for on multiple commits...
