### ISSUE TITLE
regressions: detect "ranged" regressions

### ISSUE THREAD

**Issue by pared** [airspeed-velocity/asv#932]
Following test does pass:
```
def test_regression_threshold_custom():
    steps = [(0, 1,   1.0, 1.0, 0.0),
             (1, 2,   1.04, 1.04, 0.0),
             (2, 3,   1.08, 1.08, 0.0),]

    latest, best, pos = detect_regressions(steps, threshold=0.05)
    assert pos is None
```

I think it could be useful to introduce some kind of `range` parameter that would define the maximum steps number over which regression will be detected.
That way, slow regression of the benchmarked method could also be detected across multiple commits.

**Comment by pv** [comment]
Yes, this seems to be a bug. I think how it could be expected to work is that if multiple steps are skipped due to being below the threshold, it should not skip the next one if the total regression since the first skipped step would be above the threshold.
