### ISSUE TITLE
gh-pages wipes all existing files on the branch

### ISSUE THREAD

**Issue by nabobalis** [airspeed-velocity/asv#951]
I was trying to setup asv gh-pages with a CNAME but I was unable work out how to update the gh-pages branch in a way that did not wipe the CNAME file.

Is there something I am missing in either configuration or how the command line should be called?
Or is this expected behavior?

**Comment by nicholaiTukanov** [comment]
Why did you close this issue?

**Comment by agriyakhetarpal** [comment]
Hi, were you able to find a solution for this @nabobalis? Please let it be known on this thread in case you did :)

**Comment by nabobalis** [comment]
> Why did you close this issue?

I don't remember now. 

> Hi, were you able to find a solution for this @nabobalis? Please let it be known on this thread in case you did :)

I don't think I did.
