### ISSUE TITLE
Question: How to use/extract profiling data after running 'asv run -p'

### ISSUE THREAD

**Issue by s-weigand** [airspeed-velocity/asv#971]
First of all thanks for the awesome tool ❤️ 

I'm wondering how to access the profiling data recorded when using `asv run` with the `-p` flag.
I can't find profiling anywhere in the generated HTML page (`asv publish`), nor can I find a config option or flag to add it to the HTML page (maybe I'm just blind 😅 ). 

So I'm wondering what to do after recording the profiling data.

I saw that the result json files have a key `profiles` containing benchmark names as keys and a massive text blob as value (`base64` of the `pstat` binary blob?).
So is the intended use to parse the result json file, decode the blob and then process it with a tool like `gprof2dot`?

Thanks in advance for clarifying

**Comment by mcitoler** [comment]
In my team we figured out a way to use the profile data. It uses `asv` internal classes with are poorly documented but seem to work quite well:
```python
import pstats

from asv.results import Results

results = Results.load(<file_path_to_result_json>)
profile_data_bytes = results.get_profile(<benchmark_name>)
with open(<pstats_file>, "wb") as f:
    f.write(profile_data_bytes)

p = pstats.Stats(<pstats_file>)
p.print_stats()
```
