### ISSUE TITLE
How to change the default benchmark timeout?

### ISSUE THREAD

**Issue by anmyachev** [airspeed-velocity/asv#973]
In some situations, the value of 60 seconds is not enough and I have to manually set `timeout` variable as a class attribute for each benchmark.
Is there a way to change this value for all benchmarks at once?

It would be nice to be able to customize this value through the config file or ASV CLI.

**Comment by mattip** [comment]
Help me understand the difference between setting this as a parent class attribute that all your child benchmark classes can inherit from and setting it in a config file.
