### ISSUE TITLE
readthedocs stable still documents 0.4.1 rather than the latest release, 0.4.2

### ISSUE THREAD

**Issue by anntzer** [airspeed-velocity/asv#976]
See https://asv.readthedocs.io/en/stable/.

**Comment by mattip** [comment]
I think the problem is a missing version in [the readthedocs configuration](https://readthedocs.org/projects/asv/versions/). I don't know who are the admins of the project there (I am mattip on readthedocs if the admins want help to update it).

**Comment by pv** [comment]
Added you to RTD as maintainer. Probably the RTD github integration broke in the meantime and wasn't noticed earlier.

**Comment by mattip** [comment]
Done. You should see 0.4.2 docs if you refresh the link to stable.
