### ISSUE TITLE
[Feature Request] Add a "skipped" result so skipped benchmarks don't just read "failed"

### ISSUE THREAD

**Issue by Miro-Astore** [airspeed-velocity/asv#978]
Hi, I'm pretty new to git and asv so sorry if this is misguided and not formatted properly.

I feel like it would be useful to be able to skip certain benchmarks without failiure. For example I was writing some benchmarks for a set of functions with a range of paremeters and I found that some of the combinations of parameters wasn't necessary or resulted in failiure for those functions. I was stuck either splitting up the class or keeping failiures.

 I know it's possible to skip parameters in the setup() method but it would be useful to be able to do this at the function level so large sections of the parameter space don't appear as failiures.

**Comment by CodyCBakerPhD** [comment]
@Miro-Astore It looks like this may have been added in `v0.6.0` and above - check out https://asv.readthedocs.io/en/v0.6.1/writing_benchmarks.html?highlight=skip#skipping-benchmarks

**Comment by HaoZeke** [comment]
Closing as completed
