### ISSUE TITLE
asv run fails to build wheel of project because of PEP440

### ISSUE THREAD

**Issue by Didou09** [airspeed-velocity/asv#979]
When running `asv run` in the root repo of my project (called `tofu`), `asv` correctly builds the environment (using `conda`), compiles it (it has `cython` extensions) and tries to build a wheel (for installing I guess ?).

That's when it fails because since I want to benchmark development versions of the project, the version number does not abide by `PEP440`.
The version identifier is as produced by `git describe`.

Any way to circumvent this ?
Does it mean asv can only benchmark properly tagged versions of the code ?

Here is the stdout:

![image](https://user-images.githubusercontent.com/5929562/140487375-82cb5bb1-d8ea-42f9-a7f3-2800b2dcc41a.png)

**Comment by trexfeathers** [comment]
You could override the standard `build_command` and `install_command` in `asv.conf.json`. [See here in the docs](https://asv.readthedocs.io/en/stable/asv.conf.json.html#build-command-install-command-uninstall-command).

**Comment by Didou09** [comment]
Thanks, seems to fix the issue if I add `--no-verify` to the build command.

**Comment by mattip** [comment]
Would you like to create a PR to add these solutions to the documentation, or should we close this as "it's obvious, of course that's the solution"?

**Comment by datapythonista** [comment]
I personally don't find very useful making asv create the environment for you. You can do that manually quite easily, and then use `--python=same` to avoid creating a new environment. I guess there are use cases where it makes sense, but unless you have one that requires it, I'd just do that.

@Didou09 do you think it'd make sense to add the `--no-verify` to the default conf? Closing this for now, if you think it make sense, please ping me to reopen, and feel free to contribute a PR.
