### ISSUE TITLE
Replace Appveyor by GitHub Actions

### ISSUE THREAD

**Issue by datapythonista** [airspeed-velocity/asv#985]
What are others thoughts on using GitHub Actions for the CI? Probably not a huge difference, but seems slightly simpler not to run in cygwin, would allow for Windows+Linux builds, I guess it comes with a larger quota, and I think it's becoming more standard, so it may be easier to maintain for most people.

**Comment by fangchenli** [comment]
I was playing with GitHub Actions on my asv fork https://github.com/fangchenli/asv. I have linux and macOS builds with python 3.7, 3.8 on GitHub Actions. They all have test failures related to environment creation. But the Appveyor build was always green.

**Comment by datapythonista** [comment]
Thanks @fangchenli that's very useful to know. We'll be releasing what's in master early next week, and after that aim at having a larger matrix in the CI, so we can make sure asv works with different OSs and Python versions.

**Comment by HaoZeke** [comment]
Done.
