### ISSUE TITLE
PEP8/Flake8 Maximum Length Limit

### ISSUE THREAD

**Issue by dorothykiz1** [airspeed-velocity/asv#987]
What are your preferences as regards to the maximum line length?  
It would be okay to increase the line length limit up to 99 characters, provided that comments are still wrapped at 72 characters.

PEP8 requires limiting lines to 79 characters and this in most tools disrupts the visual structure of the code, making it more difficult to understand and also an unusual indentation to fit these standards.

**Comment by datapythonista** [comment]
Set to 99 in #1003.
