### ISSUE TITLE
Run pandas benchmarks with asv master

### ISSUE THREAD

**Issue by datapythonista** [airspeed-velocity/asv#998]
In order to release asv with more confidence, we agreed to run (at least) pandas benchmarks with the latest (master branch) version of asv.

In order to do that, we simply need to have a development environment of asv (a virtual environment with a clone of this repo installed on it), have a clone of the pandas repo, and run the pandas benchmarks directory with the asv of the environment.

Once the benchmarks are run, it'd be great to post the logs as a comment in this issue.

@LucyJimenez @dorothykiz1 can you take care of this please?

**Comment by datapythonista** [comment]
@jbrockmendel Looks like `asv run` with both asv and pandas latest master works fine, without errors. You can see the full log of the execution here: [pandas_master_benchmarks_with_asv_master.log](https://github.com/airspeed-velocity/asv/files/8007125/pandas_master_benchmarks_with_asv_master.log)

Is there any other command that you'd like to test before the release, or happy to release now?

**Comment by jbrockmendel** [comment]
Nope, go for it.

**Comment by datapythonista** [comment]
Great, thanks!
